updates and fixes

diff --git a/centauridisk b/centauridisk
--- a/centauridisk
+++ b/centauridisk
@@ -3,7 +3,7 @@
 CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2017-2025; BSD License"
 CEN_TITLE="Partition a hard disk and install centauri linux"
 
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.28:4' 0 4 || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -m bat -r -y - '0.29:6' 0 4 || exit 2
 
 # Data
 CEN_OPT_BIOS=                   # see --bios
@@ -43,11 +43,11 @@ do_prefix() {
     [ -n "$DAT_PREFIX" ] && return
     local pref
     while : ; do
-        read -r -N 16 pref </dev/urandom || fatal "Cannot read from /dev/urandom"
+        read -r -N 16 pref </dev/urandom || fatal $"Cannot read from /dev/urandom"
         system -f -p -r -s pref base64 <<<$pref
         [ "${#pref}" -gt 10 ] && break
     done
-    pref="${pref//\//%}"
+    pref="${pref//[+\/]/%}"
     pref="${pref:3:6}" ; DAT_PREFIX="${pref^}"
 }
 
@@ -55,7 +55,7 @@ do_prefix() {
 # Create Partition table: mbr|msdos efi|bios
 # ------------------------------------------------------------------------------
 do_partition() {
-    local spar="${1,,}" styp="${2,,}" parts offs=0 pars=0 parb=1 parf="boot"
+    local spar="${1,,}" styp="${2,,}" parts offs=0 pars=0 parb=1 parf='boot'
     local fsys="${CEN_OPT_FSOPT:-none}" ppre
     blkdevice -n 9 -- "$CEN_OPT_DEVICE" ; ppre="${CEN_BLKDEVICE[1]%9}"
     DAT_PART_EFI=
@@ -65,7 +65,7 @@ do_partition() {
     DAT_PART_VOL0=
     DAT_PART_VOL1=
     local boos=512              # minimum size of boot partition [MB]
-    if [ "$CEN_OPT_FILE" = "0" ] ; then
+    if [ "$CEN_OPT_FILE" = 0 ] ; then
         boos=$((boos + 4096))
     elif [ -n "$CEN_OPT_FILE" ] ; then
         boos=$((boos + (CEN_OPT_FILE+7) / 8 * 8))
@@ -74,53 +74,55 @@ do_partition() {
     # add partition to parts string: <name> <type> <size>
     ___add_part() {
         local ptyp="$2" pbeg="${offs}MiB" pend ; offs=$((offs + $3))
-        [ "$pbeg" = "0MiB" ] && pbeg="0%"
+        [ "$pbeg" = '0MiB' ] && pbeg='0%'
         pend="${offs}MiB" ; [ "$3" = 0 ] && pend="${CEN_OPT_USAGE:-100}%"
-        [ "$ptyp" = "vfat" ] && ptyp="fat32"
-        [ "$ptyp" = "f2fs" ] && ptyp=
+        [ "$ptyp" = 'vfat' ] && ptyp='fat32'
+        [ "$ptyp" = 'f2fs' ] && ptyp=
         parts+="mkpart $1 $ptyp $pbeg $pend " ; pars=$((pars + 1))
     }
 
-    message -a "Creating $1 partition table..."
+    message -a -p $"Creating '%s' partition table..." "$1"
 
-    if [ "$spar" = "gpt" ] ; then
-        if [ "$styp" = "efi" ] ; then
-            ___add_part "_boot" "fat32" $boos ; DAT_PART_EFI="${ppre}1"
+    if [ "$spar" = 'gpt' ] ; then
+        if [ "$styp" = 'efi' ] ; then
+            ___add_part '_boot' 'fat32' $boos ; DAT_PART_EFI="${ppre}1"
         fi
         if [ -n "$styp" ] ; then
-            ___add_part "_grub" "" 8 ; DAT_PART_GRUB="$ppre$pars"
+            ___add_part '_grub' '' 8 ; DAT_PART_GRUB="$ppre$pars"
         fi
         if [ -n "$CEN_OPT_PART" ] ; then
-            ___add_part "_swap" "linux-swap" $(((CEN_OPT_PART*1024+7) / 8 * 8))
+            ___add_part '_swap' 'linux-swap' $(((CEN_OPT_PART*1024+7) / 8 * 8))
             DAT_PART_SWAP="$ppre$pars"
         fi
-        ___add_part "_vol0" "$fsys" 0 ; DAT_PART_VOL0="$ppre$pars"
-        if [ "$styp" = "efi" ] ; then
-            parts+="set 1 esp  on set 2 bios_grub on "
+        ___add_part '_vol0' "$fsys" 0 ; DAT_PART_VOL0="$ppre$pars"
+        if [ "$styp" = 'efi' ] ; then
+            parts+='set 1 esp  on set 2 bios_grub on '
         elif [ -n "$styp" ] ; then
-            parts+="set 1 bios_grub on "
+            parts+='set 1 bios_grub on '
         fi
-     elif [ "$spar" = "msdos" ] ; then
-         if [ "$styp" = "efi" ] ; then
+     elif [ "$spar" = 'msdos' ] ; then
+         if [ "$styp" = 'efi' ] ; then
              offs=2
-             ___add_part "primary" "fat32" $boos ; DAT_PART_EFI="${ppre}1" ; parf="esp"
+             ___add_part 'primary' 'fat32' $boos ; DAT_PART_EFI="${ppre}1" ; parf='esp'
          elif [ -n "$CEN_OPT_RASPI" ] ; then
-            ___add_part "primary" "fat32" $CEN_OPT_RASPI ; DAT_PART_EFI="${ppre}1" ; parf="lba"
+            ___add_part 'primary' 'fat32' $CEN_OPT_RASPI ; DAT_PART_EFI="${ppre}1" ; parf='lba'
          fi
          if [ -n "$CEN_OPT_PART" ] ; then
-             ___add_part "primary" "linux-swap" $(((CEN_OPT_PART*1024+7) / 8 * 8))
+             ___add_part 'primary' 'linux-swap' $(((CEN_OPT_PART*1024+7) / 8 * 8))
              DAT_PART_SWAP="$ppre$pars"
-             [ "$styp" != "efi" ] && parb=2
+             [ "$styp" != 'efi' ] && parb=2
          fi
-         ___add_part "primary" "$fsys" 0 ; DAT_PART_VOL0="$ppre$pars"
+         ___add_part 'primary' "$fsys" 0 ; DAT_PART_VOL0="$ppre$pars"
          [ -n "$styp" -a -n "$parf" ] && parts+="set $parb $parf on"
     else
-        fatal "Bad do_partition arg: $spar"
+        fatal $"Bad do_partition arg:" "$spar"
     fi
 
     # zerofill 32MByte before parted to prevent udisk from mounting garbage
     system -e -p -- dd if=/dev/zero of="$CEN_OPT_DEVICE" bs=1M count=32
     system -e -p parted --script -a optimal "$CEN_OPT_DEVICE" mklabel "$spar" $parts
+    [ -n "$DAT_PART_GRUB" ] &&
+        system -e -p -- dd if=/dev/zero of="$DAT_PART_GRUB" bs=1M count=1
     error -t || return
 
     if ! dryrun "sleep 1" ; then
@@ -134,7 +136,7 @@ do_partition() {
     [ -n "$CEN_OPT_RASPI" ] && btyp="BOOT"
     if [ -n "$btyp" ] ; then
         message -a -p "Formatting %s partition..." "$btyp"
-        local labl="${DAT_PREFIX_DISK:-$CEN_OPT_NAME}_boot"
+        local labl="${DAT_PREFIX_DISK:-$CEN_OPT_NAME}" ; labl="${labl%%[_-]*}_boot"
         if [ "${#labl}" -gt 11 ] ; then
             do_prefix ; labl="${DAT_PREFIX}_boot"
             DAT_CLONE_BOOT="$DAT_PREFIX"
@@ -150,25 +152,28 @@ do_partition() {
 do_boot() {
     local dboo="$1" drfs="$2"
     if [ "${DAT_ARCH_BOOT:--}" != '-' ] ; then
-        message -a "Restoring boot data ..."
+        message -a $"Restoring boot data ..."
         local opts=()
         optmake -a opts -n 'boot' -v "$dboo"
         if [ "$CEN_OPT_NAME" != "$DAT_SYS_NAME" ] ; then
             optmake -a opts -n 'clone' -v "$CEN_OPT_NAME"
         fi
-        embed -z -y -v centaurirestore "${opts[@]}" "$DAT_ARCH_BOOT"
+        embed -v centaurirestore --yes "${opts[@]}" "$DAT_ARCH_BOOT"
         error -t || return
     fi
 
     # install bios grub only if we have no EFI folder
     if [ -z "$CEN_OPT_BIOS" ] ; then
         if [ -d "$dboo/EFI" ] || [ -d "$dboo/efi" ]  ; then
-            message "EFI boot, not installing BIOS grub"
+            message $"EFI boot, not installing BIOS grub"
         else
             CEN_OPT_BIOS=1
         fi
     fi
-    if [ -n "$CEN_OPT_BIOS" ] ; then
+
+    if [ -n "$CEN_OPT_RASPI" ] ; then
+        message "Raspberry PI, not installing BIOS grub"
+    elif [ -n "$CEN_OPT_BIOS" ] ; then
         message -a "Installing BIOS grub ..."
         local item targ snam gdes="$dboo" pref
         [ "$CEN_OPT_FSOPT" = 'btrfs' ] && pref='/Volumes/Root'
@@ -218,7 +223,7 @@ do_boot() {
 # ------------------------------------------------------------------------------
 do_install() {
     local lopt='-l' fvol fboo mode="$1" ; shift
-    local labl="${DAT_PREFIX_DISK:-$CEN_OPT_NAME}_vol0"
+    local labl="${DAT_PREFIX_DISK:-$CEN_OPT_NAME}" ; labl="${labl%%[_-]*}_vol0"
     folder -r -f -m -s fboo -t "${CEN_NAME}_$$_boot"
     folder -r -f -m -s fvol -t "${CEN_NAME}_$$_vol0"
     DAT_MOUNT_BOOT="$fboo" ; DAT_MOUNT_VOL0="$fvol"
@@ -241,18 +246,19 @@ do_install() {
             system -e -p -t -- mkfs -t "${CEN_OPT_FSOPT:-ext4}" $lopt "$labl" "$DAT_PART_VOL0"
             system -e -p -t -- mount "$DAT_PART_VOL0" "$fvol"
         fi
+        folder -m "$froo/dev"                       # flag as root device
     fi
 
     if error -t && [ "${1:--}${2:--}${3:--}" != '---' ] ; then
         message -a "Restoring system data ..."
         local opts=()
-        optmake -a opts -n 'mount' -v "$fvol" ; optmake -a opts -n 'unmount' -f 1
+        optmake -a opts -n 'restore' -v "$fvol"
         if [ "$CEN_OPT_NAME" != "$DAT_SYS_NAME" ] ; then
             optmake -a opts -n 'clone' -v "$CEN_OPT_NAME"
             optmake -a opts -n 'clone' -v "${DAT_CLONE_BOOT:-+}"
             optmake -a opts -n 'clone' -v "${DAT_CLONE_DISK:-+}"
         fi
-        embed -z -y -v centaurirestore "${opts[@]}" "$@"
+        embed -v centaurirestore --yes "${opts[@]}" "$@"
     fi
 
     if error -t ; then
@@ -285,24 +291,28 @@ do_umount() {
 run() {
     [ "${#CEN_CMDOPTS[@]}" = 0 -a "$#" = 0 ] && main --help
     [ -n "$CEN_OPT_FILE" -a -n "$CEN_OPT_PART" ] &&
-        quit -e "Options '--part' and '--swap' are exclusive"
+        quit -e $"Options '--part' and '--swap' are exclusive"
 
     if [ -n "$CEN_OPT_RASPI" ] ; then                   # raspberry /boot
         CEN_OPT_BIOS=1 ; CEN_OPT_MSDOS=1 ; DAT_NO_BOOT=2
         if [ "$CEN_OPT_RASPI" -lt 256 ] ; then
             CEN_OPT_RASPI=256
-            warning -a -p "Boot partition size minimum is %s MByte" "$CEN_OPT_RASPI"
+            warning -a -p $"Boot partition size minimum is %s MByte" "$CEN_OPT_RASPI"
         fi
+    fi
+
+    if [ "$CEN_OPT_PART" = 0 ] ; then
+        warning -a -p $"Not creating a swap partition" ; CEN_OPT_PART=
     fi
 
     if [ -n "$CEN_OPT_USAGE" ] ; then
         [ "$CEN_OPT_USAGE" -lt 1 -o "$CEN_OPT_USAGE" -gt 100 ] &&
-            quit -e "Option '--usage' value must be in range 1..100"
+            quit -e $"Option '--usage' value must be in range 1..100"
         [ "$CEN_OPT_USAGE" = 100 ] && CEN_OPT_USAGE=
     fi
 
     local args=() bfil bdir rena
-    [ -z "$CEN_OPT_DEVICE" ] && quit -e "Missing '--device' option"
+    [ -z "$CEN_OPT_DEVICE" ] && quit -e $"Missing '--device' option"
     blkdevice -d -e -- "$CEN_OPT_DEVICE" || return
     CEN_OPT_DEVICE="$CEN_BLKDEVICE"
 
@@ -312,62 +322,62 @@ run() {
     for bfil in "$@" ; do
         args+=("$bfil")
         [ "${bfil:--}" = '-' -o "$bfil" = "+" ] && continue
-        [ -r "$bfil" ] || error "Cannot read: $bfil"
+        [ -r "$bfil" ] || error $"Cannot read:" "$bfil"
         if [ -z "$DAT_SYS_NAME" ] ; then
             bdir="${bfil%/*}" ; [ "$bdir" = "$bfil" ] && bdir="."
             bfil="${bfil##*/}"
             DAT_ARCH_BOOT="$bdir/${bfil/_*_/_boot_}"
-            DAT_SYS_NAME="${bfil%%_*}"
+            DAT_SYS_NAME="${bfil%%[_-]*}"
         fi
     done
 
     if [ "$1$2$3" = '-' ] ; then
-        message -a "Creating a non-bootable data volume"
+        message -a $"Creating a non-bootable data volume"
         DAT_NO_BOOT=1
         [ -z "$CEN_OPT_VOLUME" ] && CEN_OPT_VOLUME='-'
     else
-        [ "${1:--}${2:--}${3:--}" = "---" ] && warning -a "No system restore data"
+        [ "${1:--}${2:--}${3:--}" = "---" ] && warning -a $"No system restore data"
 
         [ -n "$4" -a "$4" != "+" ] && DAT_ARCH_BOOT="$4"
         [ "$4" = '-' ] && DAT_ARCH_BOOT=
         if [ -z "$DAT_ARCH_BOOT" ] ; then
-            [ -z "$CEN_OPT_BIOS" ] && warning -a "No EFI restore data"
-            [ -n "$CEN_OPT_RASPI" ] && warning -a "No RASPBERRY boot data"
+            [ -z "$CEN_OPT_BIOS" ] && warning -a $"No EFI restore data"
+            [ -n "$CEN_OPT_RASPI" ] && warning -a $"No RASPBERRY boot data"
         elif [ "${4:--}" != '-' ] ; then
-            [ -n "$CEN_OPT_BIOS" ] && error "EFI restore data with '--bios'"
+            [ -n "$CEN_OPT_BIOS" ] && error $"EFI restore data with '--bios'"
         else
             [ -n "$CEN_OPT_BIOS" -a -z "$CEN_OPT_RASPI" ] && DAT_ARCH_BOOT=
         fi
-        [ -n "$DAT_ARCH_BOOT" -a ! -r "$DAT_ARCH_BOOT" ] && error "Cannot read:" "$DAT_ARCH_BOOT"
+        [ -n "$DAT_ARCH_BOOT" -a ! -r "$DAT_ARCH_BOOT" ] && error $"Cannot read:" "$DAT_ARCH_BOOT"
     fi
 
     error -q ; context -r -t +
-    DAT_HOOK_QUIT="$CEN_HOOK_QUIT" ; CEN_HOOK_QUIT="hook_quit"
+    DAT_HOOK_QUIT="$CEN_HOOK_QUIT" ; CEN_HOOK_QUIT='hook_quit'
 
     # get name
     [ -z "$CEN_OPT_NAME" ] && CEN_OPT_NAME="$DAT_SYS_NAME"
-    [ -z "$CEN_OPT_NAME" ] && error "No system name (need '--name' option)"
+    [ -z "$CEN_OPT_NAME" ] && error $"No system name (need '--name' option)"
     error -t || return
 
     if [ "$CEN_OPT_NAME" = "$HOSTNAME" ] ; then
-        warning -a "Destination name equal to hostname (consider using '--name')"
-        if confirm -a -q "Do you want to continue using random disk labels" ; then
+        warning -a $"Destination name equal to hostname (consider using '--name')"
+        if confirm -a -q $"Do you want to continue using random disk labels" ; then
             do_prefix
             DAT_CLONE_BOOT="$DAT_PREFIX"
             DAT_CLONE_DISK="$DAT_PREFIX"
             DAT_PREFIX_DISK="$DAT_PREFIX"
-            rena=" (using label prefix '$DAT_PREFIX')"
+            rena=$" (using label prefix '$DAT_PREFIX')"
         fi
     elif [ "$CEN_OPT_NAME" != "$DAT_SYS_NAME" ] ; then
-        rena=" (renamed from '$DAT_SYS_NAME')"
+        rena=$" (renamed from '$DAT_SYS_NAME')"
     fi
 
     # make partitions and call installer
-    local styp="EFI" spar="GPT"
-    [ -n "$CEN_OPT_MSDOS" ] && spar="MSDOS"
+    local styp='EFI' spar='GPT'
+    [ -n "$CEN_OPT_MSDOS" ] && spar='MSDOS'
     [ -n "$CEN_OPT_BIOS"  ] && styp='BIOS'
     [ -n "$DAT_NO_BOOT"   ] && styp=
-    [ -n "$CEN_OPT_RASPI" ] && styp="RASPBERRY"
+    [ -n "$CEN_OPT_RASPI" ] && styp='RASPBERRY'
 
     confirm -a "Create ${styp:--}/$spar partitions on '$CEN_OPT_DEVICE'" || quit -t
     do_partition "$spar" "$styp"
@@ -392,29 +402,29 @@ options() {
     case "$1" in
 
     -0|--vfa|--vfat)
-        optarg "vfat"   CEN_OPT_FSOPT -f "vfat" ;;
+        optarg 'vfat'   CEN_OPT_FSOPT -f 'vfat' ;;
     -2|--fs2*)
-        optarg "fs2fs"  CEN_OPT_FSOPT -f "f2fs" ;;
+        optarg 'fs2fs'  CEN_OPT_FSOPT -f 'f2fs' ;;
     -4|--ext|--ext4)
-        optarg "ext4"   CEN_OPT_FSOPT -f "ext4" ;;
+        optarg 'ext4'   CEN_OPT_FSOPT -f 'ext4' ;;
     -B|--bio|--bios)
-        optarg "bios"   -                  ;;   # simple flag
+        optarg 'bios'   -                  ;;   # simple flag
     -D|--dev*)
-        optarg "device" -              -t  ;;   # text
+        optarg 'device' -              -t  ;;   # text
     -M|--mbr|--dos|--msdos)
-        optarg "msdos"  -                  ;;
+        optarg 'msdos'  -                  ;;
     -N|--nam|--name)
-        optarg "name"   -              -t  ;;   # text
+        optarg 'name'   -              -h  ;;   # text
     -P|--par*)
-        optarg "part"   -              -n  ;;   # number
+        optarg 'part'   -              -n  ;;   # number
     -R|--ras*)
-        optarg "raspi"  -              -n  ;;   # number
+        optarg 'raspi'  -              -n  ;;   # number
     -S|--swa|--swap)
-        optarg "swap"   CEN_OPT_FILE   -n  ;;   # number
+        optarg 'swap'   CEN_OPT_FILE   -n  ;;   # number
     -U|--usa*)
-        optarg "usage"  -              -n  ;;   # number
+        optarg 'usage'  -              -n  ;;   # number
     -V|--vol*)
-        optarg "volume" -              -t  ;;   # text
+        optarg 'volume' -              -t  ;;   # text
 
     esac
 }
diff --git a/centaurihass b/centaurihass
--- a/centaurihass
+++ b/centaurihass
@@ -23,17 +23,20 @@ DAT_USER="$DAT_NAME"                    # system user name
 DAT_VENV="$DAT_BASE/venv"               # python virtualenv
 DAT_ENAB="$DAT_VENV/service-enabled"    # custom, see autorun action
 DAT_EXEC="$DAT_VENV/bin/hass"           # weewx daemon
+DAT_PORT=8123
 
 # map quirks, HA version to minimal python version
 DAT_VERSIONS=('2024.3.3' '3.11:0'       # debian bookworm last 3.11 version
               '2025.1.4' '3.12:1'       # known working 3.12 version
-              '2025.5.3' '3.13:2'       # debian trixie
+#             '2025.5.3' '3.13:2'       # debian trixie
+              '2025.8.2' '3.13:3'       # debian trixie
              )
 
 # see https://wheels.home-assistant.io/musllinux-index/... for wheel versions
 DAT_QUIRKS=('|certbot'                  # 0 post-install
             '|certbot'                  # 1
             ''                          # 2
+            'ciso8601 lru-dict'         # 3 pre-install
            )
 
 # started as an appliance?
@@ -119,14 +122,14 @@ inst_extra_pre() {
 
     [ -z "$1" ] && return 0
     if (($1 & 2)) ; then
-        trace -a $"Installation of extra packages disabled" ; return 0
+        trace -a -c ' ' $"Installation of extra packages disabled" ; return 0
     fi
 
     local item="${DAT_QUIRKS[DAT_QUIRK]}" ; item="${item%%|*}"
     if [ -z "${item// /}" ] ; then
-        trace -a $"No extra packages to install" ; return 0
+        trace -a -c ' ' $"No extra packages to install" ; return 0
     fi
-    system -e $slnt -- pip3 install $item       # return status
+    sysrun -e -g 0 $slnt -- pip3 install $item      # return status
 }
 
 inst_extra_post() {
@@ -135,10 +138,11 @@ inst_extra_post() {
     (($1 & 2)) && return 0
 
     local item="${DAT_QUIRKS[DAT_QUIRK]}" ; item="${item##*|}"
+    [ "$item" = "${DAT_QUIRKS[DAT_QUIRK]}" ] && item=
     if [ -z "${item// /}" ] ; then
-        trace -a $"No extra packages to install" ; return 0
+        trace -a -c ' ' $"No extra packages to install" ; return 0
     fi
-    system -e $slnt -- pip3 install $item       # return status
+    system -e -g 0 $slnt -- pip3 install $item      # return status
 }
 
 # ------------------------------------------------------------------------------
@@ -157,7 +161,7 @@ inst_packages() {
     # fall back to native apt
     local slnt ; [ -n "$CEN_OPT_SILENT" ] && slnt='-p'
     [ -n "$oupd" ] && system -t -e $slnt -- apt update
-    system -t -e $slnt -- apt --yes install "$@"
+    system -t -g 0 -e $slnt -- apt --yes install "$@"
 }
 
 # ------------------------------------------------------------------------------
@@ -278,14 +282,15 @@ venv_setup() {
         done
 
         if vers_quirk ; then
-            system -p -- python3 -m venv "$DAT_VENV" || return 1
+            system -e -g 0 -p -- python3 -m venv "$DAT_VENV" || return 1
         else
-            system -p -- "python$DAT_PYVER" -m venv "$DAT_VENV" || return 1
+            system -e -g 0 -p -- "python$DAT_PYVER" -m venv "$DAT_VENV" || return 1
         fi
         message -a $"Using python virtual environment:" "$DAT_VENV"
     fi
 
-    [ -e "$DAT_VENV/bin/activate" ] && source "$DAT_VENV/bin/activate" && return 0
+    sysfind -d                                      # MUST DROP CACHED PATHS!
+    embed -n -b -- "$DAT_VENV/bin/activate" && return 0
     error $"Failed to activate python environment:" "$DAT_VENV" ; return 1
 }
 
@@ -479,7 +484,7 @@ actionSetup() {
     folder -c -f "$DAT_BASE"
     vers_quirk
 
-    local slnt cpip="$1" ; [ -n "$CEN_OPT_SILENT" ] && slnt='-q'
+    local slnt cpip ; [ -n "$CEN_OPT_SILENT" ] && slnt='-q'
     local what="$DAT_NAME"
     if [ "$1" = 'install' ] ; then
         venv_setup -c || return
@@ -501,10 +506,10 @@ actionSetup() {
         confirm -y -f $"Continue to upgrade %s" "$DAT_NICK" || return
         [ "${CEN_OPT_VERSION:--}" = '-' ] || what+="==$CEN_OPT_VERSION"
         [ -n "$slnt" ] && progress -a -l -- $"Upgrading..."
-        cpip='upgrade'
+        cpip='--upgrade'
      fi
      inst_extra_pre "${CEN_OPT_QUIRK:-0}" || return
-     system -e -- pip3 $slnt install "--$cpip" "$what" || return
+     system -e -g 0 -- pip3 $slnt install $cpip "$what" || return
      inst_extra_post "${CEN_OPT_QUIRK:-0}" || return
      [ -n "$slnt" ] && error -t && message -a -- $"Done."
 }
@@ -627,31 +632,26 @@ actionWeb() {
     local wurl="${1:--}" mode
 
     case "$wurl" in
-    http://*:[0-9]*)
+    http://*:[0-9]*|https://*:[0-9]*)
         ;;
-    https://*:[0-9]*)
-        ;;
-    http://*)
-        wurl+=':8123'
-        ;;
-    https://*)
-        wurl+=':8123'
+    http://*|https://*)
+        wurl+=":$DAT_PORT"
         ;;
     *:[0-9]*)
         wurl="http://$wurl"
         ;;
     -)  if [ -f "$DAT_ENAB" ] && check_enabled "$DAT_SERV" ; then
-            if ! echo 2>/dev/null >'/dev/tcp/localhost/8123' ; then
+            if ! echo 2>/dev/null >"/dev/tcp/localhost/$DAT_PORT" ; then
                 quit -e $"Cannot connect to '%s'" "$DAT_NICK"
             fi
-            wurl="http://localhost:8123"
+            wurl="http://localhost:$DAT_PORT"
         elif [ -z "$CEN_PACKAGE" ] ; then           # centauri-bash-lib only ...
             if nethost "$DAT_NAME" || nethost 'hass' ; then
-                wurl="http://$_nethost_ip:8123"
+                wurl="http://$_nethost_ip:$DAT_PORT"
             fi
         fi
         ;;
-    *)  wurl="http://$wurl:8123"
+    *)  wurl="http://$wurl:$DAT_PORT"
     esac
 
     if [ "$wurl" = '-' ] ; then
@@ -750,7 +750,7 @@ usage() {
         -p '<bits>'               $"1 - https://github.com/pascallj/python3.x-backport'" \
         -p ''                     $"2 - do not install extra packages" \
         -p '<user>'               $"linux user name" \
-        -p '<url>'                $"something like 'http://your-host:8123'" \
+        -p '<url>'                $"something like 'http://your-host:$DAT_PORT'" \
         -p '<vers>'               $"$DAT_NICK version to install" \
 
     usageset \
diff --git a/centauripackage b/centauripackage
--- a/centauripackage
+++ b/centauripackage
@@ -135,7 +135,8 @@ process_apt() {
 
     ___aptgui() {
         if [ -z "$CEN_OPT_SILENT" ] || [ "$CEN_VERB" -gt 1 ] ; then
-            system -e -p -z -- "$@" ; return
+            system -- "$@" && return 0
+            error -p $"The 'apt' command failed (status %s)" "$?"
         fi
         [ -z "$COLUMNS" ] && system -q -s COLUMNS -- tput cols
         local snam="${CEN_EMBED:-$CEN_NAME}" cols="${COLUMNS:-100}"
@@ -143,7 +144,7 @@ process_apt() {
 
         ___aptgui_orig() {
             DEBIAN_FRONTEND=noninteractive LC_MESSAGES=C DISPLAY= COLUMNS=$cols NO_COLOR=yes \
-            system -e "$@" --yes -o Dpkg::Options::='--force-confold' 2>&1 </dev/null ; echo STAT=$?
+            system "$@" --yes -o Dpkg::Options::='--force-confold' 2>&1 </dev/null ; echo STAT=$?
         }
 
         ___aptgui_dest() {
@@ -193,11 +194,11 @@ process_apt() {
                 *)  ___aptmsg "$poll" "$last" ; last=
                 esac
             done
-            [ "$stat" = 0 ] || error -p $"The 'apt' command failed (status %s)" "$stat"
             return "$stat"
         }
 
-        syspipe -b ___aptgui_orig -d ___aptgui_dest -- "$@"
+        syspipe -q -b ___aptgui_orig -d ___aptgui_dest -- "$@" && return 0
+        error -p $"The 'apt' command failed (status %s)" "$?"
     }
 
     ___aptyes() {
diff --git a/centauriroute b/centauriroute
--- a/centauriroute
+++ b/centauriroute
@@ -15,7 +15,7 @@ CEN_SVC_SHORT="Interface/Route Configuration"
 ### END INIT INFO
 
 # Import the bash library, set name and version
-PATH+=":/usr/local/bin:${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.46:6' || exit 2
+PATH+=":/usr/local/bin:${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.47:6' || exit 2
 
 # don't run as a service if centauriswitch is active
 inhibit "Inhibited by centauriswitch"
@@ -210,21 +210,17 @@ do_address() {
 # When <conf> is set the 'open/close/dial/hangup' actions are allowed.
 # -----------------------------------------------------------------------------
 do_cmdline() {
-    DAT_SWITCH_MODE=
-    DAT_SWITCH_CONF=
-    local line larg conf
+    local wrds word conf
     if override -r 'centauiswitch' DAT_SWITCH_MODE ; then
         invoke -w "Using 'centauiswitch=$DAT_SWITCH_MODE' from override file"
     elif [ -n "$1$2" ] ; then
         DAT_SWITCH_MODE="$1"
         DAT_SWITCH_CONF="$2"
     else
-        read -a larg </proc/cmdline
-        for line in "${larg[@]}" ; do
-            if [ "${line::15}" = 'centauriswitch=' ] ; then
-                DAT_SWITCH_MODE="${line:15}" ; break
-            fi
-        done
+        readline -e -a wrds -i '/proc/cmdline'  # get the boot parameters
+        listsearch -g -m word -i wrds -- 'centauriswitch=*'
+        DAT_SWITCH_MODE="${word:15}"
+        DAT_SWITCH_CONF=
     fi
 
     # check for <mode>:<conf>
@@ -239,15 +235,19 @@ do_cmdline() {
 
     # check mode
     case "$DAT_SWITCH_MODE" in
-    '')         message -a "Network mode not set, see 'centauiswitch=<mode>'" ; return 1 ;;
-    dis*)       DAT_SWITCH_MODE='disabled' ;;
-    sta*)       DAT_SWITCH_MODE='static'   ; conf=0 ;;
-    sim*)       DAT_SWITCH_MODE='simple'   ; conf=0 ;;
-    sma*)       DAT_SWITCH_MODE='smart'    ; conf=0 ;;
-    swi*)       DAT_SWITCH_MODE='switch'   ; conf=1 ;;
-    rou*)       DAT_SWITCH_MODE='router'   ; conf=1 ;;
-    *)          DAT_SWITCH_CONF= ; conf=2
+    '')     message -a "Network mode not set, see 'centauiswitch=<mode>'" ; return 1 ;;
+    dis*)   DAT_SWITCH_MODE='disabled' ;;
+    man*)   DAT_SWITCH_MODE='manual' ;;
+    sta*)   DAT_SWITCH_MODE='static' ; conf=0 ;;
+    sim*)   DAT_SWITCH_MODE='simple' ; conf=0 ;;
+    sma*)   DAT_SWITCH_MODE='smart'  ; conf=0 ;;
+    swi*)   DAT_SWITCH_MODE='switch' ; conf=1 ;;
+    rou*)   DAT_SWITCH_MODE='router' ; conf=1 ;;
+    ext*)   DAT_SWITCH_MODE='switch' ; conf=1 ; DAT_SWITCH_CONF='extender' ;;
+    rep*)   DAT_SWITCH_MODE='router' ; conf=1 ; DAT_SWITCH_CONF='repeater' ;;
+    *)      DAT_SWITCH_CONF= ; conf=2
     esac
+    trace -a -c '+' "Network mode=$DAT_SWITCH_MODE  conf=$DAT_SWITCH_CONF"
 
     if [ -z "$conf" -a -n "$DAT_SWITCH_CONF" ] ; then
         conf=2
@@ -255,7 +255,7 @@ do_cmdline() {
         [ -n "$DAT_SWITCH_CONF" ] || DAT_SWITCH_CONF="$DAT_SWITCH_MODE"
     fi
     if [ "$conf" = 2 ] ; then
-        error "Invalid argument:" "centauriswitch=$DAT_SWITCH_MODE${DAT_SWITCH_CONF:+:}$DAT_SWITCH_CONF"
+        error "Invalid kernel argument:" "centauriswitch=$DAT_SWITCH_MODE${DAT_SWITCH_CONF:+:}$DAT_SWITCH_CONF"
         DAT_SWITCH_CONF= ; return 1
     fi
 
diff --git a/centaurisoho b/centaurisoho
--- a/centaurisoho
+++ b/centaurisoho
@@ -5,7 +5,7 @@ CEN_TITLE=$"Installer tool for centaurisoho linux machines"
 
 # Import the bash library
 if [ -z "$CEN_NAME" ] ; then
-    PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m con -t -y - '0.22:6' || exit 2
+    PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m con -t -y - '0.23:6' || exit 2
 fi
 
 # Variable naming scopes ...
@@ -68,13 +68,15 @@ declare DAT_REPOSITORY DAT_RASPI
 # Protect the development system
 # ------------------------------------------------------------------------------
 allowInstall() {
-    # explicitly allowed ...
-    [ -n "$CEN_OPT_FORCE" ] && return 0
-    [ "$CEN_ACTION" = 'restore' ] && return 0
-
     # protect the development system ...
     local fcfg="$CEN_PERSISTENT/$CEN_NAME-conf"
     [ -f "$fcfg" ] && return 0
+
+    # explicitly allowed ...
+    if [ -n "$CEN_OPT_FORCE" ] ; then
+        create -- "$fcfg" ; return 0
+    fi
+    [ "$CEN_ACTION" = 'restore' ] && return 0
 
     local mesg=$"I am not daring to execute '%s' on this system. To allow"
           mesg+='\n'
@@ -302,6 +304,8 @@ cfg_apply() {
         get_yesno -y $"Update configuration of local host" || quit -a -u
         wrks="$SOHO_WORKSPACE" ; dest='/'
         [ "$name" = '-' ] && name="$HOSTNAME" || SOHO_HOST="$name"
+    elif [ "$para" = '+' ] ; then
+        get_yesno -n $"Reconfigure the restored system" || return
     else
 
         # install to an image? Get workspace and params  ...
@@ -352,8 +356,7 @@ cfg_apply() {
             else
                 cfg_params -q "$dcfg" || return 1
             fi
-#            confirm -d - -p $" [y/n/q]? " -v $"yes no quit" $"Apply configuration"
-             get_yesno -q $"Apply configuration changes"
+            get_yesno -q $"Apply configuration changes"
             case $? in
             0)  break ;;
             1)  ;;
@@ -362,8 +365,6 @@ cfg_apply() {
         done
         ;;
     -)  cfg_params -r || return 1 ;;
-    #-)  get_yesno -q $"Apply configuration changes" || quit -a -u
-    #    cfg_params -r || return 1 ;;
     *)  cfg_params -r "$para" || return 1
     esac
     if [ "$para" != '-' ] ; then
@@ -419,7 +420,7 @@ cfg_wlan() {
     local host="${1:-$HOSTNAME}" ; shift
     local pasw="${SOHO_NET_WLAN_PW:--}"
     if [ "$pasw" = '-' ] ; then
-        warning $"WLAN password set to random, use 'centaurinetgen' to fix"
+        warning $"WLAN password set to random, use 'centaurinetgen wpa' to fix (after reboot)"
     else
         trace -a $"Setting wlan password"
     fi
@@ -589,12 +590,14 @@ get_netcache() {
 #   -l      symlink @shared (implies -e)
 # ------------------------------------------------------------------------------
 get_repository() {
-    local conf
+    local conf notf
     # get from configuration ...
-    [ -z "$DAT_REPOSITORY" -a -n "$SOHO_CONFIG" ] &&
+    if [ -z "$DAT_REPOSITORY" -a -n "$SOHO_CONFIG" ] ; then
         for conf in "$SOHO_CONFIG" "$SOHO_DNAME" ; do
             repository -q folder DAT_REPOSITORY "$SOHO_DISTRO" "$conf" - "$DAT_SOHO_ROOT" && break
         done
+        [ "$1" = '-e' ] && [ ! -d "$DAT_REPOSITORY" ] && notf=1
+    fi
 
     # or get current repository ...
     if [ -z "$DAT_REPOSITORY" -a "$1" != '-l' ] && [ -d "$CEN_ROOT/shared" ] ; then
@@ -603,16 +606,16 @@ get_repository() {
         trace -a -c ' ' "$DAT_REPOSITORY" ; return 0
     fi
 
-    if [ -n "$DAT_REPOSITORY" ] ; then
+    if [ -n "$DAT_REPOSITORY" -a -z "$notf" ] ; then
         [ "$1" = '-l' ] && symlink -f -n -- "$DAT_REPOSITORY/@shared" "$CEN_ROOT/shared"
         trace -a -c " $1" "$DAT_REPOSITORY" ; return 0
     elif [ "$1" != '-e' -a "$1" != '-l' ] ; then
-        error -n "Missing '$CEN_ROOT/shared', please create manually by" \
-                 "running: ln -s $CEN_ROOT/configs/<dist>/<conf>/@shared $CEN_ROOT/shared"
+        error -m $"Missing '$CEN_ROOT/shared', please create manually by" \
+                 $"running:"" ln -s $CEN_ROOT/configs/<dist>/<conf>/@shared $CEN_ROOT/shared"
     elif [ -n "$SOHO_CONFIG" ] ; then
-        error "Cannot find repository '%s' or '%s'" "$SOHO_DNAME" "$SOHO_CONFIG"
+        error -p $"Cannot find repository '%s'" "$SOHO_CONFIG"
     else
-        error "Cannot find repository"
+        error $"Cannot find repository"
     fi
     return 1
 }
@@ -1088,7 +1091,7 @@ copyFromRepo() {
       --) shift ; break ;;
       -c) get_repository || return 1                    # get repo path
           [ -d "$DAT_REPOSITORY/$2" ] && return 0
-          confirm -n -f "Host '%s' not found in repository. Continue anyhow" "$2" && return 0
+          confirm -n -f $"Host '%s' not found in repository. Continue anyhow" "$2" && return 0
           quit -a -u ;;
       -l) link=' -l' ;;                                 # make symlink
       -r) get_repository -l ; return ;;                 # return status
@@ -1097,8 +1100,8 @@ copyFromRepo() {
        *) _cen_abort - "$1"
       esac ; shift
     done
-    get_repository || return 1                          # get repo path
-    trace -a -c -- "$link$fupd" "$@"
+    get_repository -e || quit -t                        # get repo path
+    trace -a -c ' ' -- "$link$fupd" "$@"
 
     local dest="${2:--}" dflt="$3" name glob            # destination path
     if [ -n "$link" ] ; then
@@ -1133,7 +1136,7 @@ copyFromRepo() {
                                                         # get 1st existing file
     if ! matchpath -o -e -s repo -- "${glst[@]}" ; then
         case "$dflt" in
-        '') error "File not in repository:" "$1" ; return 1 ;;
+        '') error $"File not in repository:" "$1" ; return 1 ;;
         -)  return 1 ;;
         *)  copyFromRepo "$dflt" "$dest" ; return       # return status
         esac
@@ -1171,7 +1174,8 @@ outputMessage() {
     }
     ___mesgsec() {
         [ "${1::1}" = '[' ] || return 0
-        printf -v subs '%s%-14s %3s' "$pref" "$1" "${CEN_CONFIGFILE[2]}"
+        subs="${1##*#}" ; [ "$subs" = "$1" ] && subs=
+        printf -v subs '%s%-14s %3s %s' "$pref" "${1%% *}" "${CEN_CONFIGFILE[2]}" "$subs"
         text+=("$subs") ; return 0
     }
 
@@ -1262,7 +1266,7 @@ actionBackup() {
     #      root             # ext4 (debian bootstrap)
 
     if [ "${2:--}" = '-' ] ; then
-        invoke -w "Backup of 'root' only"
+        invoke -w $"Backup of 'root' only"
     elif [ -d "$aboo" ] ; then
         prettypath -s mptb -- "$aboo"
     else
@@ -1312,7 +1316,6 @@ actionBackup() {
             *)          opts=("$snap" -B "$mptr" archive "$item")
             esac
         fi
-        #message centauribackup -O "$curr/$file" "${opts[@]}" ; continue
         embed -t centauribackup -O "$curr/$file" "${opts[@]}"
     done
 
@@ -1565,7 +1568,12 @@ actionInstall() {
 }
 
 # ------------------------------------------------------------------------------
-# Message text: <mesg> [<file>|- [<pref>]]
+# Message text: <mesg> [<file>|- [<pref>] [<subs>]]
+#
+#   <mesg>      ini-file section
+#   <file>      output file
+#   <pref>      prefix for output lines (used to indent)
+#   <subs>      replaces '%1%' in output
 # ------------------------------------------------------------------------------
 actionMessage() {
     get_workspace -n || return                      # get base folder
@@ -1890,7 +1898,7 @@ actionRestore() {
     [ -n "$item" ] && get_value name "$name" - $"Set hostname of installed image"
     [ -z "$swap" ] && get_value swap "$swad" - $"Size of swap partition in GByte"
 
-    [[ "$name" =~ [a-z][-a-z]*[a-z] ]] || quit -e $"Invalid host name:" "$name"
+    isname -e -h -- "$name" || return
     [ "$name" = "$HOSTNAME" ] && quit -e $"Cannot use current host name"
     [ -n "${swap//[0-9]}" ] && quit -e $"Invalid swap size:" "$swap"
 
@@ -1900,14 +1908,14 @@ actionRestore() {
     elif [ "${#labl[@]}" != 2 ] ; then
         error -p $"Input data unusable (%s):" "$host" "$CEN_INPFILE" ; return
     fi
-
-    if [ "$fsys" = 'ext4' ] ; then
-        opts+=('-4')
-    else                                                # btrfs uses a 'volumes' file
-        volf="${host}_volumes"
-        if [ ! -e "$volf" ] ; then                      # ext4 mode without volumes file
-            opts+=('-4') ; volf= ; fsys='ext4'
-        fi
+                                                        # btrfs uses a 'volumes' file
+    matchpath -s volf -f -o -- "${host}_volumes" "${host}-"*_volumes
+    if [ $? != 0 ] ; then                               # ext4 mode without volumes file
+        [ -z "$fsys" ] && fsys='ext4'
+    fi
+    if [ "$fsys" = 'ext4' ] ; then                      # no 'volumes for ext4
+        [ -n "$volf" ] && warning $"Restoring a 'btrfs' system to 'ext4' partition"
+        opts+=('-4') ; volf=
     fi
 
     if [ "$name" != "$host" ] ; then                    # renaming ...
@@ -1919,13 +1927,14 @@ actionRestore() {
     if [ -z "$dbug" ] ; then
         # restore root, usr, home and boot (if present)
         if [ -n "$rasp" ] ; then
-            confirm -a -y -f '%-48s' "Install '$name' in 'raspberry' mode" || return
+            confirm -a -y -f '%-48s' $"Install '$name' in 'raspberry' mode" || return
             embed -z -v centauridisk "${opts[@]}" -M -R 512 -P$swap -- "${labl[1]}"
         else
-            confirm -a -y -f '%-48s' "Install '$name' in 'x86/pc' mode" || return
+            confirm -a -y -f '%-48s' $"Install '$name' in 'x86/pc' mode" || return
             embed -z -v centauridisk "${opts[@]}" -P$swap -- "${labl[1]}"
         fi
     fi
+    error -t || return
 
     # mount destination partition
     system -e -p -r -- partprobe ; sleep 1
@@ -1936,7 +1945,7 @@ actionRestore() {
         [ "$name" != "$host" ] && samba_check -i "$CEN_MOUNT_DIR"
 
         if [ -h "$CEN_MOUNT_DIR/boot/efi" ] || [ -d "$CEN_MOUNT_DIR/boot/efi" ] ; then
-            message "This system is configured to boot via EFI"
+            message $"This system is configured to boot via EFI"
         fi
     fi
 
@@ -1946,7 +1955,7 @@ actionRestore() {
         # all btrfs systems update-grub should already be diverted by cloning
 
         [ -d "$CEN_MOUNT_DIR/boot/grub" ] || break
-        message -a "Replacing 'grub.cfg' with 'grub.minimal'"
+        message -a $"Replacing 'grub.cfg' with 'grub.minimal'"
         # shellcheck disable=SC2034
         local gcfg stab="s/^set myname=.*/set myname=$name/"
         system -e -p -s gcfg -- sed -e "$stab" 'grub.minimal' || break
@@ -1954,7 +1963,7 @@ actionRestore() {
 
         [ -x "$CEN_MOUNT_DIR/usr/sbin/udate-grub.distrib" ] && break
         targ='/usr/sbin/update-grub'
-        message -a "Diverting '$targ' to noop"
+        message -a $"Diverting '$targ' to noop"
         system -e -p dpkg-divert --root="$CEN_MOUNT_DIR" --rename --add "$targ" || break
         targ="$CEN_MOUNT_DIR$targ"
         dryrun "<script $targ>" && break
@@ -1979,9 +1988,9 @@ actionRestore() {
             *)
                 # shellcheck disable=SC2086
                 matchpath -e -o -s tarf -- *_${item,}_*
-                message -a -p "Extra volume: %s  Tar file: %s" "$item" "${tarf:--}"
+                message -a -p $"Extra volume: %s  Tar file: %s" "$item" "${tarf:--}"
                 if [ ! -d "$CEN_MOUNT_DIR/Volumes" ] ; then
-                    error "Missing folder:" "$CEN_MOUNT_DIR/Volumes"
+                    error $"Missing folder:" "$CEN_MOUNT_DIR/Volumes"
                     break
                 fi
                 volu="$CEN_MOUNT_DIR/Volumes/$item"
@@ -1999,7 +2008,7 @@ actionRestore() {
         for file in *_export_*.tar* *_shared_*.tar* ; do
             [ -f "$file" ] || continue
             item="${file#*_}" ; item="${item%%_*}"
-            message -a -p "Extra folder: %s  Tar file: %s" "$item" "$file"
+            message -a -p $"Extra folder: %s  Tar file: %s" "$item" "$file"
             item="$CEN_MOUNT_DIR/$item"
             folder -m -- "$item" || break
             system -e -p tar -C "$item" -xaf "$file" || break
@@ -2009,7 +2018,7 @@ actionRestore() {
     # appl='' do nothing, appl=1 do query or params, appl=2 network only
     if [ "$appl" = 1 ] ; then
         # 3 args: do parameter-file or query update
-        cfg_apply "$CEN_MOUNT_DIR" "$name" "$para"
+        cfg_apply "$CEN_MOUNT_DIR" "$name" "${para:-+}"
     elif [ -n "$appl" ] ; then
         # 2 args: system was renamed, need wpa update
         cfg_apply "$CEN_MOUNT_DIR" "$name" -
@@ -2038,7 +2047,7 @@ actionSetup() {
 
     # Updated seed tar, must restart. Ignore this if called by setup
     if [ -z "$CEN_OPT_DISPATCH" ] && [ "$DAT_SEED" -nt '.timestamp' ] ; then
-        trace "The seed tar was updated, must restart after unpacking"
+        trace $"The seed tar was updated, must restart after unpacking"
         dryrun -s "unpack/restart" && quit -t -a
         run_installer 'install'
         # install replaced our sources, so we must restart now ...
@@ -2061,12 +2070,16 @@ actionSetup() {
 
     dryrun -s 'setup' && return                 # setup does not handle dryrun
 
-    trace -p "Calling '%s' in 'setup' script" "$CEN_OPT_DISPATCH"
+    if [ ! -h "/etc/network/interfaces" ] && netoption 'sysdnames' "$HOSTNAME" ; then
+        warning -p "Should not have option 'sysdnames' for '%s' host" "$HOSTNAME"
+    fi
+
+    trace -p $"Calling '%s' in 'setup' script" "$CEN_OPT_DISPATCH"
     # shellcheck disable=SC2034
     [ -n "${CEN_CMDARGS[CEN_CMDINDX]}" ] && DAT_NOT_LAST=1 || DAT_NOT_LAST=
     # shellcheck disable=SC2086
     isfunction -c -e --  "$CEN_OPT_DISPATCH" $verb "$@"
-    trace -p "Returned from '%s'" "$CEN_OPT_DISPATCH"
+    trace -p $"Returned from '%s'" "$CEN_OPT_DISPATCH"
 }
 
 # ------------------------------------------------------------------------------
