Little fixes, centauridiff -M folders

diff --git a/centauriraspi b/centauriraspi
--- a/centauriraspi
+++ b/centauriraspi
@@ -11,6 +11,7 @@ PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m mnt -t -y - '0.24:2' || exit 2
 CEN_OPT_BOOT=               # see --boot
 CEN_OPT_DEVICE=             # see --device
 CEN_OPT_HOST="$HOSTNAME"    # see --host
+CEN_OPT_IFNAMES=            # see --ifnames
 CEN_OPT_LEGACY=             # see --legacy
 CEN_OPT_NOCHECK=            # see --nocheck
 CEN_OPT_ROOT=               # see --root
@@ -286,24 +287,27 @@ actionEntry() {
         fi
         do_ask_quit -f "Booting '%s' from '%s' filesystem. Continue" "$CEN_OPT_HOST" "$fsty"
     fi
+    args+=('fsck.repair=yes')
 
     if [[ "$args" =~ LABEL=.*_vol[0-9] ]] ; then    # btrfs config
-        args+=(rootflags=subvol=/Volumes/Root)
+        args+=('rootflags=subvol=/Volumes/Root')
         if do_legacy ; then                         # pre bookworm layout
             args+=(initrd=0) ; ramd=1
         fi
-    elif [ -n "$args" ] ; then                      # ext4 config
+#   elif [ -n "$args" ] ; then                      # ext4 config
+   fi
 
- #### TODO always ...
-        args+=('fsck.repair=yes')
-    fi
-
-    # other methods are not reliable on raspberry pi os ...
-    if netoption 'sysdnames' "$CEN_OPT_HOST" ; then
-        args+=('net.ifnames=1')
-    else
-        args+=('net.ifnames=0')
-    fi
+    local ifna
+    case "$CEN_OPT_IFNAMES" in
+    0)  ifna=0 ;;
+    1)  ifna=1 ;;
+    *)  if  [ "$DAT_ETCDIR/systemd/network/99-default.link" -ef '/dev/null' ] ; then
+            ifna=0
+        elif netoption 'sysdnames' "$CEN_OPT_HOST" ; then
+            ifna=1
+        fi
+    esac
+    [ -n "$ifna" ] && args+=("net.ifnames=$ifna")
 
     case "${1:-splash}" in
     -)          ;;
@@ -411,7 +415,7 @@ actionRemove() {
 }
 
 # ------------------------------------------------------------------------------
-# set root: <config>|-|. <label>|-
+# set root: <config>|-|. <label>|-|.
 #
 #   config: <name>  use cmdline-<name>.txt
 #           -       use cmdline-default.txt
@@ -421,7 +425,7 @@ actionRemove() {
 #           <label> example: cent9_root     -> root=LABEL=<label>
 #           <uuid>  example: abcd1234-03    -> root=PARTUUID=<uuid>
 #           -       1st try 'rootfs' 2 try <hostname>_(vol0|root|rootfs)
-####           .       use PARTUUID
+#           .       use PARTUUID
 # ------------------------------------------------------------------------------
 actionRoot() {
     do_folder
@@ -437,24 +441,24 @@ actionRoot() {
 
     # no label arg, try rootfs or default to <host>
     local item part
-    #if [ "$iden" = '.' ] ; then
-    #    local list indx=0
-    #    if [ -z "$CEN_OPT_DEVICE" ] ; then
-    #        error "Option '--device' missing" ; return
-    #    fi
-    #    system -e -p -a list -- blkid --probe -o value -s TYPE -s UUID "$CEN_OPT_DEVICE" || return
-    #    while [ -n "${list[indx]}" ] ; do
-    #        if [ "${list[indx]}" = 'ext4' -o "${list[indx]}" = 'btrfs' ] ; then
-    #            iden="${list[indx+1]}" ; part="/dev/disk/by-partuuid/$iden"
-    #            message -a -p "Found 'PARTUUID=%s' with '%s' filesystem" "$iden" "${list[indx]}"
-    #            break
-    #        fi
-    #        ((indx += 2))
-    #    done
-    #    if [ "$iden" = '.' ] ; then
-    #        error 'UUID not found' ; return
-    #    fi
-    if [ "$iden" = '-' ] ; then
+    if [ "$iden" = '.' ] ; then
+        local list indx=0
+        if [ -z "$CEN_OPT_DEVICE" ] ; then
+            error "Option '--device' missing" ; return
+        fi
+        system -e -p -a list -- blkid --probe -o value -s TYPE -s UUID "$CEN_OPT_DEVICE" || return
+        while [ -n "${list[indx]}" ] ; do
+            if [ "${list[indx]}" = 'ext4' -o "${list[indx]}" = 'btrfs' ] ; then
+                iden="${list[indx+1]}" ; part="/dev/disk/by-partuuid/$iden"
+                message -a -p "Found 'PARTUUID=%s' with '%s' filesystem" "$iden" "${list[indx]}"
+                break
+            fi
+            ((indx += 2))
+        done
+        if [ "$iden" = '.' ] ; then
+            error 'UUID not found' ; return
+        fi
+    elif [ "$iden" = '-' ] ; then
         if [ -b "/dev/disk/by-label/rootfs" ] ; then
             part="/dev/disk/by-label/rootfs"
         else
@@ -567,6 +571,8 @@ options() {
         optarg 'boot'        -   -d  ;;         # existing folder
     -D|--dev*)
         optarg 'device'      -   -t  ;;         # any text
+    -F|--ifn*)
+        optarg 'ifnames'     -   -o  ;;         # ternary
     -H|--hos*)
         optarg 'host'        -   -t  ;;         # any text
     -L|--leg*)
@@ -613,6 +619,7 @@ usage() {
     usageset -o - \
        -o '-B --boot    <fldr>' $"path of boot folder         (default: /boot)" \
        -o '-D --device  <name>' $"raspberry boot device" \
+       -o '-F --ifnames <nmod>' $"systemd interface naming    (default: auto)" \
        -o '-H --host    <host>' $"override host name" \
        -o '-L --legacy  <auto>' $"pre-bookworm boot layout    (default: auto)" \
        -o '-N --nocheck'        $"don't check boot partition" \
@@ -629,7 +636,7 @@ usage() {
        -a -                     $"default parameters and 'nosplash' to disable plymouth)" \
        -a 'initrd <event>'      $"(booted system) manage initrd file" \
        -a 'remove <config>'     $"remove the given configuration" \
-       -a 'root   [<config>|-|. [<label>|<host>|<uuid>|-]]' \
+       -a 'root   [<config>|-|. [<label>|<host>|<uuid>|-|.]]' \
        -a -                     $"set 'root=' in kernel command line" \
        -a 'show'                $"Show current boot configuration"
 
@@ -641,6 +648,7 @@ usage() {
        -p '<event>'     $"'create', 'update' or 'remove' (uninstall hook)" \
        -p '<fldr>'      $"any existing folder (must contain 'overlays')" \
        -p '<host>'      $"target host name (default: $HOSTNAME)" \
+       -p '<nmod>'      $"systemd naming mode: 0|off 1|on 2|auto" \
        -p '<name>'      $"system name, label or blockdevice" \
        -p '<overlay>'   $"an overlay file name (for config-*.txt)" \
        -p '<root>'      $"parameter for root=... (use '-' to disable, '+' for default)"
@@ -668,12 +676,14 @@ usage() {
        -t "$CEN_NAME --device /dev/sda1 config hdmi # set config 'hdmi'" \
        -t "$CEN_NAME --boot /mnt/boot show          # explicit folder" \
        -t - \
-       -t "$CEN_NAME entry server worm3_vol0        # create a cmdline file" \
+       -t "$CEN_NAME entry -                        # create default cmdline files" \
+       -t "$CEN_NAME entry server worm3_vol0        # create specific cmdline file" \
        -t "$CEN_NAME config server                  # select 'server' config" \
        -t - \
        -t "$CEN_NAME root                           # boot from <host>_root" \
-       -t "$CEN_NAME root . raspi4                  # boot from raspi4_root" \
-       -t "$CEN_NAME root - 5d50dd2e-03             # set default PARTUUID" \
+       -t "$CEN_NAME root . raspi4                  # boot via label raspi4_root" \
+       -t "$CEN_NAME root - .                       # boot via current PARTUUID" \
+       -t "$CEN_NAME root - 5d50dd2e-03             # boot via specific PARTUUID" \
        -t "$CEN_NAME root sdcard /dev/sdb3          # set sdcard config" \
        -t - \
        -t "$CEN_NAME initrd                         # create/update, set hook"
diff --git a/centaurisecrets b/centaurisecrets
--- a/centaurisecrets
+++ b/centaurisecrets
@@ -16,8 +16,8 @@ CEN_SVC_SHORT="Get Domain Server and secrets"
 ### END INIT INFO
 
 # Import the bash library, set name and version (--dryrun NOT FULLY IMPLEMENTED)
-PATH+=":/usr/local/bin"
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.56:2' || exit 2
+PATH+=':/usr/local/bin'
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -v - '0.57:2' || exit 2
 
 # Extra option data
 CEN_OPT_NOHOOK=                         # see --nohook
@@ -46,7 +46,7 @@ DAT_DIR_SECRETS="$CEN_ROOT/secrets"             # main secrets folder
 DAT_DIR_DOWNLOAD="$DAT_DIR_TEMP/secrets-load"   # temporary download folder
 DAT_DIR_FAKE="$DAT_DIR_TEMP/secrets-fake"       # server fake data folder
 DAT_DIR_LOCAL="$DAT_DIR_SECRETS/local"          # server static data folder
-DAT_DIR_STATIC="$DAT_DIR_SECRETS/data"          # ... (sent to clients)
+DAT_DIR_STATIC="$DAT_DIR_SECRETS/data"  # ... (sent to clients)
 
 DAT_MACHINE_DIR="$CEN_ROOT/machines"    # per-machine secrets folder
 DAT_MACHINE_ID=                         # machine-id
@@ -74,7 +74,7 @@ umask 022
 # -----------------------------------------------------------------------------
 is_static() {
     # status is known already?
-    [ "$CEN_SECRETS_MODE" = "static" ] && return 0
+    [ "$CEN_SECRETS_MODE" = 'static' ] && return 0
     [ "${CEN_SECRETS_MODE:-unknown}" != "unknown" ] && return 1
     [ "$1" = "-r" ] && return 1
 
@@ -83,19 +83,19 @@ is_static() {
 
     # the data folder makes secrets 'static', e.g. not downloaded
     if [ -d "$DAT_DIR_STATIC" ] ; then
-        CEN_SECRETS_MODE="static"
+        CEN_SECRETS_MODE='static'
         remove -d "$DAT_DIR_SECRETS/import"
 
         if [ ! -d "$DAT_MACHINE_DIR" ] ; then
             netquery MASTER && folder -m -f "$DAT_MACHINE_DIR" 770 root:wheel
         fi
     else
-        CEN_SECRETS_MODE="download"
+        CEN_SECRETS_MODE='download'
         folder -m -f "$DAT_DIR_DOWNLOAD" 711 root:root
         symlink -m -n -r "$DAT_DIR_DOWNLOAD" "$DAT_DIR_SECRETS/import"
     fi
 
-    [ "$CEN_SECRETS_MODE" = "static" ]      # return status
+    [ "$CEN_SECRETS_MODE" = 'static' ]      # return status
 }
 
 # -----------------------------------------------------------------------------
@@ -115,13 +115,13 @@ do_active() {
     # special case: am I a server?
     local inam="$HOSTNAME.$CEN_NET_DOMAIN"
     if [ "$inam" = "$svr1" ] ; then             # I am primary, check secondary
-        svr1="$svr2" ; svr2="--"
+        svr1="$svr2" ; svr2='--'
     elif [ "$inam" = "$svr2" ] ; then           # I am secondary, check primary
-        svr2="--"
+        svr2='--'
     fi
 
     # yes, I am a server
-    if [ "$svr2" = "--" ] ; then
+    if [ "$svr2" = '--' ] ; then
         [ "$DAT_HOST" != "${DAT_SERVER[0]}" -a "$DAT_HOST" != "${DAT_SERVER[1]}" ] &&
             error "I am a server - ignoring server argument: $DAT_HOST"
         if [ "${svr1:--}" = '-' ] ; then
@@ -175,7 +175,7 @@ do_active() {
     if [ -n "$DAT_PORT_POLL" -a "$CEN_OPT_POLL" != "ping" ] ; then
 
         # i am server - check 2nd server only for running ldap
-        if [ "$svr2" = "--" ] ; then
+        if [ "$svr2" = '--' ] ; then
             type -t -f netcat >/dev/null 2>&1 ||
                 fatal "Required 'netcat' is no installed"
             pri1="netcat -z -w3 $svr1 $DAT_PORT_POLL"
@@ -213,7 +213,7 @@ do_active() {
         # progress repeort  (phase 0 := initial call)
         if [ "$1" -gt 0 ] ; then
             local mesg="$svr1"
-            [ "$1" -gt 1 -a "$svr2" != "--" ] && mesg+=" $svr2"
+            [ "$1" -gt 1 -a "$svr2" != '--' ] && mesg+=" $svr2"
             message -i "Retry server check: $mesg"
             progress "." ; [ -n "$wait" ] && sleep "$wait"
         fi
@@ -251,7 +251,7 @@ do_active() {
         message "Server is active: $hnam"
         DAT_ACTIVE="$hnam" ; DAT_HOST="$hnam" ; return 0
     fi
-    if [ "$svr2" = "--" ] ; then
+    if [ "$svr2" = '--' ] ; then
         message "Server '$svr1' not active, I am MASTER"
         DAT_BLOCKED1="$svr1"
         DAT_ACTIVE="$inam" ; DAT_HOST="$inam" ; return 0
@@ -509,15 +509,20 @@ do_names() {
         case "$1" in
         --)     shift ; break ;;
         -r)     oref=1 ;;
-        -p)     otyp="p" ;;
-        -s)     otyp="s" ;;
-        *)      fatal "do_names bad arg: $1"
+        -p)     otyp='p' ;;
+        -s)     otyp='s' ;;
+        *)      fatal -t '-' "$1"
         esac ; shift
     done
 
     # initial load or refresh data
     if [ -n "$oref" -o -z "${DAT_CENTAURINAME[0]}" ] ; then
-        embed -a DAT_CENTAURINAME -r centauriname --qual --nick --homedns --active --server
+        netquery -f -q -r -s \
+                       DAT_CENTAURINAME[0] 'server'
+        netquery -q -s DAT_CENTAURINAME[1] 'homedns'
+        netquery -q -s DAT_CENTAURINAME[2] 'MASTER'
+        netquery -q -s DAT_CENTAURINAME[3] 'primary'
+        netquery -q -s DAT_CENTAURINAME[4] 'secondary'
         DAT_ACTIVE="${DAT_CENTAURINAME[2]}"
     fi
 
@@ -656,10 +661,10 @@ do_secrets() {
 do_server() {
     # get options
     local maid refr coun
-    if [ "$1" = "-m" ] ; then                   # machine id only
+    if [ "$1" = '-m' ] ; then                   # machine id only
         maid=1 ; shift
-    elif [ "$1" = "-r" ] ; then                 # refresh host
-        refr="-r" ; shift
+    elif [ "$1" = '-r' ] ; then                 # refresh host
+        refr='-r' ; shift
     fi
     if [ "${1::1}" = '-' ] ; then               # invalid arg -or- local
         DAT_HOST= ; DAT_SERVER=()
@@ -669,12 +674,11 @@ do_server() {
     # get machine id
     if [ -z "$DAT_MACHINE_ID" ] ; then
         local dmid='/var/lib/dbus/machine-id'
-        if [ ! "/etc/machine-id" -ef "$dmid" ] ; then
+        if [ ! '/etc/machine-id' -ef "$dmid" ] ; then
             error "$dmid should be a symlink to /etc/machine-id"
             return 1
         fi
-        [ -r "/etc/machine-id" ] &&
-            DAT_MACHINE_ID="$(< /var/lib/dbus/machine-id)"
+        readline -w -s DAT_MACHINE_ID -i '/etc/machine-id'
     fi
     [ -n "$maid" ] && return 0
 
@@ -692,7 +696,7 @@ do_server() {
             do_names "$1" ; DAT_HOST="$_do_names"
             # have no known server
             if [ -z "$DAT_HOST" ] ; then
-                nettemp "centauriswitch" && . "$_nettemp"
+                nettemp 'centauriswitch' && source "$_nettemp"
                 if  [ "$DAT_SWITCH_MODE" = 'static' ] ; then
                     DAT_SERVER[0]="${DAT_CENTAURINAME[3]}"
                     DAT_SERVER[1]="${DAT_CENTAURINAME[4]}"
@@ -720,7 +724,7 @@ do_status() {
         [ -n "$CEN_SECRETS_MODE" ] && return 0          # already loaded
         CEN_SECRETS_HOST=
         CEN_SECRETS_WHAT=
-        CEN_SECRETS_MODE="unknown"
+        CEN_SECRETS_MODE='unknown'
         CEN_SECRETS_IFACE=
         [ -r "$DAT_DIR_TEMP/$CEN_NAME" ] || return 1
         . "$DAT_DIR_TEMP/$CEN_NAME" ;       return 0
@@ -732,7 +736,7 @@ do_status() {
     # prepare data
     [ "$2" = '-' ] || CEN_SECRETS_HOST="$2"
     [ "$3" = '-' ] || CEN_SECRETS_WHAT="$3"
-    [ -n "$CEN_SECRETS_MODE" ] || CEN_SECRETS_MODE="unknown"
+    [ -n "$CEN_SECRETS_MODE" ] || CEN_SECRETS_MODE='unknown'
     dryrun do_status "$*" && return 0
 
     # write
@@ -744,12 +748,13 @@ ${CEN_SECRETS_MODE@A}
 ${CEN_OPT_IFACE@A}"
     create -h - -t -v mesg -- "$DAT_DIR_TEMP/$CEN_NAME"
 
-    # update /data folder. Args are: <mode> <server> <nick>
-    local what="${CEN_SECRETS_WHAT:-UNKNOWN}"
+    # update network neighborhood folder. Args are: <mode> <server> <nick>
+    local neig what="${CEN_SECRETS_WHAT:-UNKNOWN}"
     if [ "$what" = 'UNKNOWN' ] ; then               # home/guest network offline
-        if ! [ '/data/home' -ef '/home' ] ; then
-            embed -v centauridata --quiet update "$what" &
-        fi
+        shortpath -a neig -e 'network' &&
+            if ! [ "$neig/home" -ef '/home' ] ; then
+                embed -v centauridata --quiet update "$what" &
+            fi
     else                                            # home/guest network online
         embed -v centauridata --quiet update "$what" "$CEN_SECRETS_HOST" "$DAT_CENTAURINAME" &
     fi
@@ -800,8 +805,8 @@ actionMachines() {
     done
 
     # create/protect folders
-    folder -m "@other" 770 "root:wheel"
-    system -e -p -- chown "root:wheel" . "${dirs[@]}"
+    folder -m "@other" 770 'root:wheel'
+    system -e -p -- chown 'root:wheel' . "${dirs[@]}"
     system -e -p -- chmod 770 . "${dirs[@]}"
 
     # update keytabs
@@ -817,14 +822,17 @@ actionMachines() {
 actionRegister() {
     do_server -r "$1" || return                 # get home server
     local sdir="$DAT_MACHINE_DIR/$HOSTNAME"
-    local verb ; [ "$CEN_VERB" -gt 1 ] && verb='-v'
-
+    local opts=() conf
+    netquery -s conf 'config'
     sysversion -u || return
-    message -p "Register host '%s (%s)' at server '%s'" "$HOSTNAME" "$CEN_SYS_NICKNAME" "$DAT_HOST"
-    [ -n "$CEN_SYS_NICKNAME" ] && verb+=" --nick $CEN_SYS_NICKNAME"
-    [ -n "$CEN_OPT_FORCE" ] && verb+=" --force"
-    system -e -- ssh -x "root@$DAT_HOST" \
-        centaurimachines $verb --add "$HOSTNAME/$DAT_MACHINE_ID"
+    message -p "Register host '%s (%s)' at server '%s'" \
+        "$HOSTNAME" "$CEN_SYS_NICKNAME:$conf" "$DAT_HOST"
+    optmake -a opts -b 'verbose'
+    optmake -a opts -b 'force'
+    optmake -a opts -n 'nick'   "$CEN_SYS_NICKNAME"
+    optmake -a opts -n 'domain' "$conf"
+    optmake -a opts -n 'add'    "$HOSTNAME/$DAT_MACHINE_ID"
+    system -e -- ssh -x "root@$DAT_HOST" centaurimachines "${opts[@]}"
 }
 
 # -----------------------------------------------------------------------------
@@ -977,8 +985,8 @@ actionServer() {
         fi
         folder -c -f "$mdir"
 
-        [ -f "krb5.keytab" ] && sadd="--add-file=./krb5.keytab "
-        [ -f "repository.conf" ] && sadd+="--add-file=./repository.conf "
+        [ -f 'krb5.keytab' ] && sadd="--add-file=./krb5.keytab "
+        [ -f 'repository.conf' ] && sadd+="--add-file=./repository.conf "
 
     # no machine dir (are we a guest server?)
     else
diff --git a/centauristartup b/centauristartup
--- a/centauristartup
+++ b/centauristartup
@@ -3,20 +3,18 @@
 CEN_LEGAL=$"Dr. Jürgen Pfennig (c) 2020-2024; BSD License"
 CEN_TITLE=$"Network mode and GUI selection menu"
 
-PATH+=":${0%/*}" . _centauri_bash_lib  -a -d -t - '0.10:2' 1 || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib  -a -d -t - '0.20:2' 1 || exit 2
 
 # global data
 
 CEN_OPT_HASS=                   # see --hass
 CEN_OPT_KIOSK=                  # see --kiosk
 
-DAT_LOGIN='centaurilogin'
 DAT_TRAP=                       # see trap_handler
 
 # invoke 'menu' action if called via .autologin symlink (see centaurisession)
 if [ "$CEN_NAME" = '.autologin' ] ; then
     CEN_NAME='centauristartup'
-    # bash --noprofile --norc ; exit
     if [ $# = 0 ] ; then
         [ "$USER" = 'kiosk' ] && CEN_OPT_KIOSK=1
         set -- menu
@@ -76,7 +74,7 @@ show_display() {
     }
     DAT_RUN_MODES=()
     ___disp 0 'desktop'     $"show single-user Desktop"
-    ___disp 1 'kiosk' $"enter Kiosk mode"
+    ___disp 1 'kiosk'       $"enter Kiosk mode"
     ___disp 0 'workstation' $"enter Multi-User mode"
     ___disp 0 'maintenance' $"enter Maintenance mode"
     ___disp 0 'network'     $"change Network setup"
@@ -198,21 +196,22 @@ actionDesktop() {
 # Install/uninstall: -no args-
 # ------------------------------------------------------------------------------
 actionInstall() {
+    local want="${CEN_PATHS[2]}/systemd/system/getty.target.wants"
+    remove "$want/centauriautologin"*                   # cleanup to be prudent
+
     if [ "$CEN_ACTION" = 'install' ] ; then
         if [ ! "$CEN_TOOLS/$CEN_NAME" -ef ~local/'.autologin' ] && [ -d ~local ] ; then
             symlink -n -- "$CEN_TOOLS/$CEN_NAME" ~local/'.autologin'
-     #       system -e -p -- systemctl enable  "$CEN_ROOT/systemd/system/centauriautologin@local.service"
         fi
         if [ ! "$CEN_TOOLS/$CEN_NAME" -ef ~kiosk/'.autologin' ] && [ -d ~kiosk ] ; then
             symlink -n -- "$CEN_TOOLS/$CEN_NAME" ~kiosk/'.autologin'
-     #       system -e -p -- systemctl enable  "$CEN_ROOT/systemd/system/centauriautologin@kiosk.service"
         fi
         [ -d ~homeassistant ] &&
                          symlink -n -- "$CEN_TOOLS/$CEN_NAME" ~homeassistant/'.autologin'
+        symlink -n -- "$CEN_ROOT/systemd/system/centauriautologin.service" \
+                      "$want/centauriautologin@.service"
     else
         remove ~local/'.autologin' ~kiosk/'.autologin' ~homeassistant/'.autologin'
-    #    system -q -- systemctl disable  "$CEN_ROOT/systemd/system/centauriautologin@local.service"
-    #    system -q -- systemctl disable  "$CEN_ROOT/systemd/system/centauriautologin@kiosk.service"
     fi
 }
 
@@ -294,8 +293,20 @@ actionMenu() {
 
         while : ; do
             [ -n "$DAT_TRAP" ] && break     # back to network dialog
-            [ "$CEN_OPT_KIOSK" = 1 ] && tout=5
-            if ! show_display mgui "${cgui:-desktop}" "$cgui" $tout ; then
+            if [ "${CEN_OPT_KIOSK:-0}" != 0 ] ;then
+                # using /etc/X11/xinit/xinit.rc to run a script ...
+                create -c -- ".$CEN_NAME" 755 <<!EOF
+#!/usr/bin/bash
+
+# This script gets called from xinitrc:
+#    see /etc/bash.centauri -> centaurisession -> centauristartx
+
+export XDG_CURRENT_DESKTOP=xinit
+exec /admin/centaurilauncher kiosk "http://localhost"
+!EOF
+                do_root 'kiosk' "$USER"
+                show_shutdown ; continue
+            elif ! show_display mgui "${cgui:-desktop}" "$cgui" $tout ; then
                 tout=
                 show_shutdown ; continue
             fi
