Update api level 4

diff --git a/centaurisecrets b/centaurisecrets
--- a/centaurisecrets
+++ b/centaurisecrets
@@ -157,7 +157,7 @@ do_active() {
     fi
     while ! ___ifwait "${ilst[@]}" ; do
         # do not wait in smart or router mode (these use networkmanage orr dhcp hooks)
-        nettemp "centauriswitch" && . "$_nettemp"
+        nettemp -s 'centauriswitch'
         if ! [ "$DAT_SWITCH_MODE" = 'smart' -o  "$DAT_SWITCH_MODE" = 'router' ] ; then
             message "No interface is up - waiting..."
             timer -w 3 ; ___ifwait "${ilst[@]}" && break
@@ -215,7 +215,7 @@ do_active() {
             local mesg="$svr1"
             [ "$1" -gt 1 -a "$svr2" != '--' ] && mesg+=" $svr2"
             message -i "Retry server check: $mesg"
-            progress "." ; [ -n "$wait" ] && sleep "$wait"
+            progress '.' ; [ -n "$wait" ] && sleep "$wait"
         fi
 
         # primary command   (phase 1 := primary server. 1st cmd only)
@@ -244,11 +244,11 @@ do_active() {
     # polling
     local hnam                                # set by __active
     if [ -n "$svr1" ] ; then
-        trace "Checking for server [$svr1${svr2:+ }$svr2]"
+        trace -a -c "Check for server" "[$svr1${svr2:+ }$svr2]"
         __active 0  || __active 1 || __active 2 || __active 2 || __active 3 || hnam=
     fi
     if [ -n "$hnam" ] ; then
-        message "Server is active: $hnam"
+        message -a -c "Server is active" "$hnam"
         DAT_ACTIVE="$hnam" ; DAT_HOST="$hnam" ; return 0
     fi
     if [ "$svr2" = '--' ] ; then
@@ -256,7 +256,7 @@ do_active() {
         DAT_BLOCKED1="$svr1"
         DAT_ACTIVE="$inam" ; DAT_HOST="$inam" ; return 0
     fi
-    trace -i "No active server"
+    trace -a "No active server"
     DAT_BLOCKED1="$svr1" ; DAT_BLOCKED2="$svr2" ; DAT_ACTIVE=
 
     hnam="${DAT_CENTAURINAME[1]:--}"
@@ -502,13 +502,13 @@ do_dirinit() {
 # ------------------------------------------------------------------------------
 _do_names=
 do_names() {
-    local oref otyp qval nick
+    local otyp qval nick
     _do_names=
 
     while [ "${1::1}" = '-' ] ; do
         case "$1" in
         --)     shift ; break ;;
-        -r)     oref=1 ;;
+        -r)     CEN_NET_ROLE= ; DAT_CENTAURINAME= ;;
         -p)     otyp='p' ;;
         -s)     otyp='s' ;;
         *)      fatal -t '-' "$1"
@@ -516,14 +516,15 @@ do_names() {
     done
 
     # initial load or refresh data
-    if [ -n "$oref" -o -z "${DAT_CENTAURINAME[0]}" ] ; then
-        netquery -f -q -r -s \
+    if [ -z "$DAT_CENTAURINAME" ] ; then
+        netquery -f -q -s \
                        DAT_CENTAURINAME[0] 'server'
         netquery -q -s DAT_CENTAURINAME[1] 'homedns'
         netquery -q -s DAT_CENTAURINAME[2] 'MASTER'
         netquery -q -s DAT_CENTAURINAME[3] 'primary'
         netquery -q -s DAT_CENTAURINAME[4] 'secondary'
         DAT_ACTIVE="${DAT_CENTAURINAME[2]}"
+        [ -z "${DAT_CENTAURINAME[1]}" ] && DAT_CENTAURINAME[1]='-'
     fi
 
     # explicit name given - override homedns
@@ -544,17 +545,17 @@ do_names() {
 
     # use only servers if homedns matches any (generic) server name or is 'local'
     local item fsrv hdns="${DAT_CENTAURINAME[1]}"
-    [ "$hdns" = '-' -a -z "$1" ] && return 1    # need hdns or override
+    [ -z "$hdns" -a -z "$1" ] && return 1       # need hdns or override
     for item in 'local' "${DAT_CENTAURINAME[3]}" "${DAT_CENTAURINAME[4]}" ; do
         [ "$item" = "$hdns" ] || continue
         fsrv=1 ; break
     done
 
     # what to return
-    if [ "$otyp" = "p" ] ; then
+    if [ "$otyp" = 'p' ] ; then
         [ -z "$fsrv" ] && return 1
         qval="${DAT_CENTAURINAME[3]:--}"        # primary
-    elif [ "$otyp" = "s" ] ; then
+    elif [ "$otyp" = 's' ] ; then
         [ -z "$fsrv" ] && return 1
         qval="${DAT_CENTAURINAME[4]:--}"        # secondary
     else
@@ -595,7 +596,7 @@ do_secrets() {
     __secrets() {
         if [ "$1" != '-' ] ; then
             message -i "Retry secrets load from: $DAT_HOST"
-            progress "." ; sleep 2
+            progress '.' ; sleep 2
         fi
 
         dryrun "echo $HOSTNAME $DAT_COOKIE $DAT_MACHINE_ID |"\
@@ -660,7 +661,7 @@ do_secrets() {
 # ------------------------------------------------------------------------------
 do_server() {
     # get options
-    local maid refr coun
+    local maid refr coun mesg
     if [ "$1" = '-m' ] ; then                   # machine id only
         maid=1 ; shift
     elif [ "$1" = '-r' ] ; then                 # refresh host
@@ -682,12 +683,14 @@ do_server() {
     fi
     [ -n "$maid" ] && return 0
 
-    for ((coun=0 ; coun < 15 ; coun++)) ; do
-        [ "$coun" = 0 ] || timer -w 1
+    mesg="Waiting for dhcp to provide a name server"
+    while : ; do
+        ((coun++)) && timer -w 1
 
         # get a known server - if any
         do_names $refr -p "$1" ; DAT_SERVER[0]="$_do_names"
         do_names       -s "$1" ; DAT_SERVER[1]="$_do_names"
+
         if   [ -n "${DAT_SERVER[0]}" ] ; then
             DAT_HOST="${DAT_SERVER[0]}"
         elif [ -n "${DAT_SERVER[1]}" ] ; then
@@ -696,7 +699,7 @@ do_server() {
             do_names "$1" ; DAT_HOST="$_do_names"
             # have no known server
             if [ -z "$DAT_HOST" ] ; then
-                nettemp 'centauriswitch' && source "$_nettemp"
+                nettemp -s 'centauriswitch'
                 if  [ "$DAT_SWITCH_MODE" = 'static' ] ; then
                     DAT_SERVER[0]="${DAT_CENTAURINAME[3]}"
                     DAT_SERVER[1]="${DAT_CENTAURINAME[4]}"
@@ -705,7 +708,11 @@ do_server() {
                 fi
                 [ "$CEN_ACTION" = 'auto' ] || break
                 [ "$DAT_SWITCH_MODE" = 'router' ] && break
-                message -a "Waiting to get name server from dhcp" $coun
+                case "$coun" in
+                1)      message -a "$mesg" ;;
+                6|11)   message -a -p "%s since %ss" "$mesg" $((coun-1)) ;;
+                16)     message -a "Timeout waiting for dhcp" ; break
+                esac
                 continue
             fi
         fi
@@ -727,7 +734,7 @@ do_status() {
         CEN_SECRETS_MODE='unknown'
         CEN_SECRETS_IFACE=
         [ -r "$DAT_DIR_TEMP/$CEN_NAME" ] || return 1
-        . "$DAT_DIR_TEMP/$CEN_NAME" ;       return 0
+        source "$DAT_DIR_TEMP/$CEN_NAME" ;  return 0
     fi
 
     # check temp dir (created via sys module)
@@ -824,7 +831,7 @@ actionRegister() {
     local sdir="$DAT_MACHINE_DIR/$HOSTNAME"
     local opts=() conf
     netquery -s conf 'config'
-    sysversion -u || return
+    sysversion -u                               # best efford, ignore errors
     message -p "Register host '%s (%s)' at server '%s'" \
         "$HOSTNAME" "$CEN_SYS_NICKNAME:$conf" "$DAT_HOST"
     optmake -a opts -b 'verbose'
@@ -897,6 +904,8 @@ actionSecrets() {
 
     # create or update /etc/samba/smbpasswd
     ___mkpasswd() {
+# TODO check of 'option addc'   netoption 'addc' "$HOSTNAME"
+        netquery server && return 0                     # not for a server
         local file='/etc/samba/smbpass.conf'
         if [ ! -e "$file" ] || ! system -q -c 'pdbedit' ; then
             warning "Missing samba config:" "$file" ; return
@@ -922,7 +931,7 @@ actionSecrets() {
     # load passwords from seed, make secrets files: <seed>
     ___useseed() {
         local padm ptru ppub prep psyn proo ploc
-        do_passwords "$1"
+        do_passwords "$1" || { error "Failed to read seed:" "$1" ; return ; }
         do_passwords proo 'root'
         do_passwords ploc 'local'
         do_passwords ptru 'smbtrust'
@@ -1081,31 +1090,31 @@ actions() {
     stop)
         invoke -        actionInit      0 ;;
     sta*)
-        invoke "status" -               0 ;;
+        invoke 'status' -               0 ;;
 
     # mode switching
     aut*)
-        invoke "auto"   -               0 ;;
+        invoke 'auto'   -               0 ;;
     cli*)
-        invoke "client" actionStart   0 1 ;;
+        invoke 'client' actionStart   0 1 ;;
     loc*)
         invoke 'local'  actionStart     0 ;;
 
     # other commands
     ini*)
-        invoke "init"     -           0 1 ;;
+        invoke 'init'     -           0 1 ;;
     mac*)
-        invoke "machines" -             0 ;;
+        invoke 'machines' -             0 ;;
     reg*)
-        invoke "register" -           0 1 ;;
+        invoke 'register' -           0 1 ;;
     lda|ldap)
-        invoke "ldap"     actionSecrets   ;;
+        invoke 'ldap'     actionSecrets   ;;
     sam*)
-        invoke "samba"    actionSecrets 2 ;;
+        invoke 'samba'    actionSecrets 2 ;;
     sec*)
-        invoke "secrets"  -             1 ;;
+        invoke 'secrets'  -             1 ;;
     ser*)
-        invoke "server"   -             0 ;;
+        invoke 'server'   -             0 ;;
     esac
 }
 
@@ -1138,7 +1147,7 @@ usage() {
        -a "auto                 Find an active server and download secrets." \
        -a "                     Does nothing if secrets and state are current" \
        -a "client   [<server>]  Find/check an active server and download secrets." \
-       -a "                     The default server is: "${_do_names:--}"" \
+       -a "                     The default server is: ""${_do_names:--}" \
        -a "                     No <server> arg: check if server is still valid" \
        -a "local                drop current secrets, init secrets to defaults" \
 
diff --git a/centaurisysinit b/centaurisysinit
--- a/centaurisysinit
+++ b/centaurisysinit
@@ -1,10 +1,10 @@
-#!/bin/bash
+#!/usr/bin/bash
 # ------------------------------------------------------------------------------
 CEN_LEGAL="Dr. Jürgen Pfennig (c) 2021-2024; "$"BSD License"
 CEN_TITLE=$"Centauri initialization and launcher for appliances"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -t -v -y - '0.10:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -t -v -y - '0.12:4' || exit 2
 
 CEN_SVC_WANTED_BY='sysinit.target'
 
@@ -17,8 +17,9 @@ CEN_SVC_NOROOT=1
 # folder for issue data
 DAT_ISSUE_DIR="$CEN_ROOT/persistent/issue.d"
 
-# invoke 'issue' action if called via .autologin symlink (see centaurisession)
-if [ "$CEN_NAME" = '.autologin' ] ; then
+# invoke 'issue' action if called via .centauriautologin symlink (see centaurisession)
+DAT_AUTOLOGIN='.centauriautologin'
+if [ "$CEN_NAME" = "$DAT_AUTOLOGIN" ] ; then
     CEN_NAME='centaurisysinit'
     set -- issue execute
 fi
@@ -37,32 +38,22 @@ DAT_APPL_AUTO=
 # see apptimers() ...
 DAT_APPL_TIMERS=
 # see appusers() ...
-DAT_APPL_USERS=
+DAT_APPL_USERS=                     # TODO remove this
 
 # homeassistant user
 DAT_APPL_HASS='homeassistant'
 
 # dummy functions to skip 'appliance' config lines
-appliance() { : ; }
+appliance() { : ; }     # <label> <runlevel> <mode> <conf> <param>...
 apptimers() { : ; }
 appusers()  { : ; }
 
 # get home folder: <name>
 get_home() {
-    local indx user home
-    case "$1" in
-    local)          user="${DAT_APPL_USERS[0]}" ;;
-    homeassistant)  user="${DAT_APPL_USERS[1]}" ;;
-    kiosk)          user="${DAT_APPL_USERS[2]}" ;;
-    *)              listsearch -n indx -i DAT_APPL_USERS -- "$1"
-                    [ "${indx:-0}" -gt 2 ] && user="${DAT_APPL_USERS[indx]}"
-    esac
-    [ "${user:--}" = '-' ] && user="$1"
-    eval home=~"$user"
+    local home ; eval home=~"$1"
     [ -d "$home" ] || return 2
-   # trace "USER=$user   HOME=$home"
-    [ -e "$home/.autologin" ] || return 3
-    [ "$home/.autologin" -ef '/dev/null' ] && return 4
+    [ -e "$home/$DAT_AUTOLOGIN" ] || return 3
+    [ "$home/$DAT_AUTOLOGIN" -ef '/dev/null' ] && return 4
     return 0
 }
 
@@ -86,7 +77,8 @@ get_appliances() {
              get_home "$auto" ; stat="$?"
              if [ "$stat" != 0 ] ; then
                 trace -a -c -p "Appliance ignored" "status %d - %s" "$stat" "$6"
-                return 0
+            #    return 0
+                set -- - "$2"
              fi
         fi
 
@@ -108,11 +100,11 @@ cfg_appliances() {
     local indx frmt acmd labl
     case "$1" in
     0)      [ "$CEN_ACTION" = 'default' ] || return
-            if [ -d '/boot/efi/loader' ] ; then
-                embed -v centauriefilinux -y menu 90 default 5
-            else
-                embed -v centauriraspi -y default
-            fi ; return
+            if [ -d '/boot/efi' ] && findmount '/boot/efi' ; then
+                embed -v centauriefilinux -y menu 90 default 5 ; return
+            elif [ -d '/boot/firmware' ] && findmount '/boot/firmware' ; then
+                embed -v centauriraspi -y default ; return
+            fi
             ;;
     [1-9]|1[0-9])
             indx="$(($1 - 1))"
@@ -127,7 +119,11 @@ cfg_appliances() {
 
     local name="${DAT_APPL_LABEL[indx]}" swit args=()
     case "$CEN_ACTION" in
-    enable)     acmd='create' ; frmt=$"Add appliance '%s' to boot menu" ;;
+    enable)     if [ -z "${DAT_APPL_LEVEL[indx]}" ] ; then
+                    error $"Cannot enable this appliance:" "$name"
+                    return
+                fi
+                acmd='create' ; frmt=$"Add appliance '%s' to boot menu" ;;
     disable)    acmd='delete' ; frmt=$"Remove appliance '%s' from boot menu" ;;
     *)          acmd='default' ; frmt=$"Boot as appliance '%s'" ;;
     esac
@@ -137,7 +133,7 @@ cfg_appliances() {
         local opti="${DAT_APPL_CONF[indx]}"
         if [ "${opti:--}" != '-' ] ; then
             netoption "$opti" "$HOSTNAME" ||
-                warning -p "Appliance '%s' is not in network config, no automatic setup" "$name"
+                warning -p $"Mode '%s' no configured for host, no automatic setup" "$opti"
         fi
     fi
 
@@ -149,17 +145,17 @@ cfg_appliances() {
         [ -n "${DAT_APPL_ARGS[indx]}" ] && args+=("${DAT_APPL_ARGS[indx]}")
         [ -n "${DAT_APPL_LEVEL[indx]}" ] && args+=("systemd.unit=runlevel${DAT_APPL_LEVEL[indx]}.target")
         # must register to launch the menu ...
-        [ -n "${DAT_APPL_AUTO[indx]}" ] && embed -t -v centauristartup install
+        [ -n "${DAT_APPL_AUTO[indx]}" ] && embed -t -v centauristartup -q install "${DAT_APPL_AUTO[indx]}"
     fi
 
-    if [ -d '/boot/efi/loader' ] ; then
+    if [ -d '/boot/efi' ] && findmount '/boot/efi' && [ -d '/boot/efi/loader' ] ; then
         acmd="$((indx + 41))"
         case "$CEN_ACTION" in
             enable)      embed -v centauriefilinux -y menu --- "$acmd" create "$name" "${args[@]}" ;;
             disable)     embed -v centauriefilinux -y menu --- "$acmd" delete ;;
             *)           embed -v centauriefilinux -y menu --- "$acmd" default
         esac
-    elif [ -d '/boot/firmware' ] ; then
+    elif [ -d '/boot/firmware' ] && findmount '/boot/firmware' ; then
         name="${DAT_APPL_CONF[indx]}" ; acmd=
         if [ "$name" = 'disabled' ] ; then
             name='bootmenu' ; swit='splash'
@@ -189,7 +185,7 @@ cfg_appliances() {
 # called at service start
 # ------------------------------------------------------------------------------
 run_appliances() {
-    # undo /etc/XWrapper.conf config override (see centauristartx)
+    # undo /etc/XWrapper.conf config override (see centauridisplay)
     local wrap="${CEN_PATHS[2]}/X11/Xwrapper.config"
     [ -f "$wrap.default" ] && move -q -x -- "$wrap.default" "$wrap"
 
@@ -224,45 +220,42 @@ run_appliances() {
         :
     elif [ "$levl" = 'runlevel2' ] ; then
         # networking is not configured in runlevel2
-        system -e -p -- systemctl --no-block start networking
+        system -e -p -- systemctl --no-block start networking inetd
     fi
 
     # centaurilogin action ...
     if [ -n "$auto" ] ; then
         local hdir ; eval hdir=~$auto
-        if [ "$auto" = "$DAT_APPL_HASS" ] ; then
+        if [ "$auto" = "$DAT_APPL_HASS" ] && [ -d "$hdir" ] ; then
             message -a -c $"Start service" 'centaurihass'
-            system -e -p -- systemctl --no-block start centaurihass
+            embed -v centaurihass -f start
         fi
-        if [ -e "$hdir/.autologin" ] && [ "$hdir/.autologin" != '/dev/null' ] ; then
+        if [ -e "$hdir/$DAT_AUTOLOGIN" ] && [ "$hdir/$DAT_AUTOLOGIN" != '/dev/null' ] ; then
             message -a -c $"Autologin user" "$auto"
             system -e -p -- systemctl --no-block start centauriautologin@"$auto"
         fi
     fi
 
     # 'timers' config statement
+    get_appliances
     local item list=()
     for item in "${DAT_APPL_TIMERS[@]}" 'centauriswap.service' ; do
         [ "${item%.*}" = "$item" ] && item+='.timer'
+        [ -e "/usr/lib/systemd/system/$item" -o  -e "/etc/systemd/system/$item" ] || continue
         list+=("$item")
+
     done
     # enable timers and swap ...
-    system -w -p -- systemctl --no-block start "${list[@]}"
+    [ -n "$list" ] && system -w -p -- systemctl --no-block start "${list[@]}"
+
+    # finally stop plymouth daemon
+    timer -w 10 ; system -q plymouth quit
 }
 
 # ------------------------------------------------------------------------------
 # called at service start
 # ------------------------------------------------------------------------------
 run_netconfig() {
-#    # adjust interface naming
-#    local imok='systemd'
-#    netiface -n             # stat=0 ifnames=0    stat=1 ifnames=1
-#    case "$?" in
-#    0)  imok='bios' ;;
-#    1)  remove "${CEN_PATHS[2]}/systemd/network/99-default.link" ;;
-#    *)  [ "${CEN_PATHS[2]}/systemd/network/99-default.link" -ef '/dev/null' ] && imok='bios'
-#    esac
-
     # make sure to have cached network config
     if [ "${CEN_PATHS[6]}/centaurinetcfg" -nt "$CEN_ROOT/persistent/centaurinetcfg" ] ; then
         message -c $"Network config" $"configuration update"
@@ -292,6 +285,11 @@ run() {
         echo "System startup..." >/dev/console
     fi
 
+    # migrate centauristartx to centauridisplay
+
+    symlink -n "$CEN_TOOLS/centauridisplay" '/usr/local/bin/centauridisplay'
+    symlink -n "$CEN_TOOLS/centauridisplay" '/usr/local/bin/centauristartx'
+
     # update networking
     run_netconfig
 
@@ -310,7 +308,7 @@ run() {
 # action config: [<appl>]
 # ------------------------------------------------------------------------------
 actionConfig() {
-    local indx=0 icfg frst=1 wrds=$"quit" opti optw
+    local indx=0 icfg frst=1 wrds=$"quit" opti optu optw
 
     if [ "${CEN_PATHS[6]}/centaurinetcfg" -nt "$CEN_ROOT/persistent/centaurinetcfg" ] ; then
         message $"Running full network setup"
@@ -318,9 +316,10 @@ actionConfig() {
     fi
 
     # migrate systemd boot entry 50 -> 80
-    if [ -e '/boot/entries/50-maintenance-mode-bookworm.conf' ] ; then
-        rename '/boot/entries/50-maintenance-mode-bookworm.conf' \
-               '/boot/entries/80-maintenance-mode-bookworm.conf'
+    sysversion
+    local suff="maintenance-mode-$CEN_SYS_NICKNAME.conf"
+    if [ -e "/boot/entries/50-$suff" ] ; then
+        rename "/boot/entries/50-$suff" "/boot/entries/80-$suff"
     fi
 
     get_appliances || return
@@ -340,20 +339,25 @@ actionConfig() {
         [ -z "$opti" ] && opti="${DAT_APPL_MODE[indx]}"
         if [ "$opti" = '-' ] ; then
             opti=
+        elif [ -z "${DAT_APPL_LEVEL[indx]}" ] ; then
+            opti=' [#]'
+            [ -n "$optu" ] && optu+='|'; optu+="${DAT_APPL_AUTO[indx]}"
         elif netoption "$opti" "$HOSTNAME" ; then
             opti=
         else
-            opti=' [*]' ; optw=1
+            opti=' [*]' ; optw=1 ; DAT_APPL_LEVEL[indx]=
         fi
         ((indx += 1)) ; wrds+=" $indx"
-        message -i -p '%2s: %s' "$indx" "${DAT_APPL_LABEL[indx-1]}$opti"
+        message -i -p '%2s: %-30s %s' "$indx" "${DAT_APPL_LABEL[indx-1]}" "$opti"
     done
     message -i ' '
-    if [ -n "$optw" ] ; then
+    [ -n "$optu" ] &&
+        message -i -m $"[#] This appliance is currently not enabled. To use it, please run" \
+                      $"    'centauristartup install $optu'."
+    [ -n "$optw" ] &&
         message -i -m $"[*] This appliance is not enabled by network configuration. Please" \
                       $"    adjust the appropriate 'option <what> <host>...' statement in" \
                       $"    file '/etc/default/centaurinetcfg' to enable it." ''
-    fi
     [ "$CEN_ACTION" = 'list' ] && return
     while ! confirm -p - -s icfg -v "$wrds" \
             $"Select an Appliance or hit <return> when finished"" [$frst..$indx]" ; do
@@ -369,7 +373,7 @@ actionConfig() {
 # ------------------------------------------------------------------------------
 # action config:    add   [<file> [<args>]] # must be executable to have args
 #                   clear                   # no args
-#                   exec                    # no args
+#                   exec  [<cons>]          # console#
 #                   test  <wtim>            # optional arg
 # ------------------------------------------------------------------------------
 actionIssue() {
@@ -390,7 +394,7 @@ actionIssue() {
             ;;
     1cle)   remove -d -- "$fldr" ; return
             ;;
-    1exe)   ;;
+    ?exe)   ;;
     1tes)   [ -d "$fldr" ] || quit 1 ; return
             ;;
     2tes)   if [ "$arg0" = '-' ] ; then
@@ -414,17 +418,23 @@ actionIssue() {
     if runservice status 'sddm' || runservice status 'lightdm' ; then
         timer -w 1
     else
-        timer -w 5
+        timer -w 1
+        [ "${arg0:--}" = '-' ] || system -q chvt "$arg0"
+        timer -w 3
     fi
+    [ "${arg0:--}" = '-' ] || system -q chvt "$arg0"
 
     system -q -- setupcon --current-tty
-    local item
+    local item data coun
     for item in "$@" ; do
         if [ -x "$item" ] ; then
             "$item"
         else
-            cat "$item"
-            read -N1 -p $"Press any key to continue"
+            message -p $"Issue message #%s" $((coun++))
+            echo
+            inpdata -a data -- "$item" ; outdata -a -o data
+            echo
+            read -N1 -p "$CEN_NAME: "$"Press any key to continue"
         fi
         remove -- "$item"
         clear
@@ -445,7 +455,14 @@ actionIssue() {
     [ -n "$sesi" ] && system -e -p loginctl activate "$sesi" && return
     read -N1 -t2 -p $"Cannot find active console, use <Alt><Fn> to switch manually"
     echo
-    system -q chvt 1
+    system -q chvt 2
+}
+
+# ------------------------------------------------------------------------------
+#
+# ------------------------------------------------------------------------------
+actionMode() {
+    run "centauriswitch=$1" "centauriautologin=$2" "systemd.unit=runlevel$3.target"
 }
 
 # ------------------------------------------------------------------------------
@@ -455,18 +472,17 @@ actions() {
     case "$1" in
 
     def*)
-        invoke -r 'default'    actionConfig 0 1 ;;  # one optional arg
+        invoke -r 'default'    actionConfig     0 1 ;;  # one optional arg
     dis*)
-        invoke -r 'disable'    actionConfig 0 1 ;;  # one optional arg
+        invoke -r 'disable'    actionConfig     0 1 ;;  # one optional arg
     ena*)
-        invoke -r 'enable'     actionConfig 0 1 ;;  # one optional arg
+        invoke -r 'enable'     actionConfig     0 1 ;;  # one optional arg
     iss*)
-        invoke    'issue'      -            1 + ;;  # at least one arg
+        invoke    'issue'      -                1 + ;;  # at least one arg
     lis|list)
-        invoke    'list'       actionConfig 0 ;;    # no args
-
-    #test)                                          # helper for testing
-    #   invoke    'test'       run_appliances
+        invoke    'list'       actionConfig     0   ;;  # no args
+    mod|mode)
+        invoke -r 'mode'       -                3   ;;  # three args
     esac
 }
 
@@ -474,38 +490,43 @@ actions() {
 # Print usage info
 # ------------------------------------------------------------------------------
 usage() {
-    # resolve the config folder path (/etc/default for debian)
-    prettypath -c -- "$CEN_ROOT/default/$CEN_NAME"
-
-    # more help text ...
     usageset \
-        -a 'list'               $"list configured appliances" \
-        -a 'default  [<appl>]'  $"[*] set/remove a boot default" \
-        -a 'disable  <appl>'    $"[*] disable an appliance in boot menu" \
-        -a 'enable   <appl>'    $"[*] enable an appliance in boot menu" \
-        -a - \
-        -a 'issue add  [<args>]' $"add a issue file or an exucutable" \
+        -a 'issue add'           $"add an issue text from stdin" \
+        -a 'issue add  [<argi>]' $"add a issue file or an exucutable" \
         -a 'issue clear'         $"remove any pending issues" \
-        -a 'issue execute'       $"show or run issues, used by 'centaurissues.service'" \
+        -a 'issue exec [<cons>]' $"show or run issues, used by 'centaurissues.service'" \
         -a 'issue test [<wtim>]' $"test for pending service, can wait until done" \
+        -a '••• '$"Appliance actions"' •••' - \
+        -a 'list'                $"list configured appliances" \
+        -a 'mode     <netw> <user> <rlvl>' - \
+        -a -                     $"enter an appliace mode" \
+        -a 'default  [<appl>]'   $"[*] set/remove a boot default" \
+        -a 'disable  <appl>'     $"[*] disable an appliance in boot menu" \
+        -a 'enable   <appl>'     $"[*] enable an appliance in boot menu" \
         -a - \
         -a $"[*] these actions use the 'centauriefilinux' or 'centauriraspi' tools." \
         -a $"    Grub's boot menu must be adapted manually (if used at all)."
 
     usageset \
-        -p '<appl>'              $"appliance name or index (see 'list' action)" \
+        -p '<appl>'             $"appliance name or index (see 'list' action)" \
+        -p '<argi>'             $"an executable and arguments" \
+        -p '<cons>'             $"console tty number  (usually: 8)" \
+        -p '<netw>'             $"a centauriswitch networking mode" \
+        -p '<rlvl>'             $"appliance run-level (usually: 2|3)" \
+        -p '<user>'             $"appliance user      (usually: local|kiosk|clock)" \
+        -p '<wtim>'             $"issue service test maximum wait time" \
 
     usageset \
         -t "While linux servers or workstations typically launch a stack of network" \
         -t "related services at startup (e.g. runlevel > 3), an appliance starts at" \
         -t "runlevel=2 and handles further service starts via centauriswitch configs." \
         -t - \
-        -t "$CEN_NAME sources '$CEN_PRETTYPATH' which can execute" \
+        -t "$CEN_NAME sources '${CEN_PATHS[6]}/$CEN_NAME' which can execute" \
         -t "additional startup code (like 'rc.local' once did). Optionally an array" \
         -t "named 'appliances' can be added to configure supported appliances." \
         -t - \
         -t "Appliances use <conf> from the 'centauriswitch=<mode>:<conf>' kernel boot cmd" \
-        -t "to start services and other things via '${CEN_PRETTYPATH%/*}/centauriswitch'." \
+        -t "to start services and other things via '${CEN_PATHS[6]}/centauriswitch'." \
         -t - \
         -l "issue" \
         -t "This mechanism can run programs or show messages on a console before any" \
@@ -513,11 +534,23 @@ usage() {
         -t "'$CEN_NAME execute' when '$DAT_ISSUE_DIR' exists." \
         -t - \
         -t "The 'lightdm' and 'sddm' display manager services have override files to" \
-        -t "run 'centauristartx' before starting the dm. This tool checks for pending" \
+        -t "run 'centauridisplay' before starting the dm. This tool checks for pending" \
         -t "issues to prevent the dm to switch away from the issues console." \
         -t - \
         -t "Finally 'centaurisession' (which runs at login) checks for pending issues" \
         -t "and can run a user notification."
+
+    usageset \
+        -e "# Configuration file example" \
+        -e "° appliance 'Networking Menu' 2  disabled -  'centaurilogin=local'" \
+        -e "° appliance 'Network Switch'  3  switch" \
+        -e "° appliance 'Home Assistant'  2  smart    -  'centaurilogin=homeassistant'" \
+        -e "° appliance 'Digital Clock'   2  smart    -  'centaurilogin=clock'" \
+        -e "° appliance 'Kiosk Mode'      3  simple   -  'centaurilogin=kiosk'" \
+        -e "# timers to be started in appliance modes" \
+        -e "° apptimers   anacron apt-daily apt-daily-upgrade" \
+        -e "# any bash script code to be run ..." \
+        -e "° [ -x hello-sysinit ] && hello_sysinit"
 }
 
 # ------------------------------------------------------------------------------
