new centauriinit, removed centaurildap

diff --git a/centauriraspi b/centauriraspi
--- a/centauriraspi
+++ b/centauriraspi
@@ -1,10 +1,10 @@
-#!/bin/bash
+#!/usr/bin/bash
 # ------------------------------------------------------------------------------
 CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2009-2024; "$"BSD License"
 CEN_TITLE=$"Tool to manage 'Raspberry Pi' boot configurations"
 
 # Import the bash library, set name and version
-PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m mnt -t -y - '0.23:2' || exit 2
+PATH+=":${0%/*}" . _centauri_bash_lib -a -d -f -m mnt -t -y - '0.24:2' || exit 2
 
 # Data
 
@@ -14,6 +14,7 @@ CEN_OPT_HOST="$HOSTNAME"    # see --host
 CEN_OPT_LEGACY=             # see --legacy
 CEN_OPT_NOCHECK=            # see --nocheck
 CEN_OPT_ROOT=               # see --root
+CEN_OPT_UUID=               # see --uuid
 
 DAT_UPDTHOOK="/etc/initramfs/post-update.d/$CEN_NAME"
 DAT_ASK_QUIT=
@@ -37,7 +38,7 @@ do_file() {
             printf -v "$1" '%s' "${CEN_MATCHPATH#$2-}"
             return 0
         fi
-        invoke -e $"Ambigous seletion:" "$3" ; return 1
+        invoke -e $"Ambigous selection:" "$3" ; return 1
     fi
     [ "$2" = 'config' ] || invoke -e $"No matching file:" "$3"
     return 1
@@ -101,7 +102,7 @@ do_initrd() {
         create -d "${DAT_UPDTHOOK%/*}" || return 1
         folder -f -m "$CEN_OPT_ROOT${DAT_UPDTHOOK%/*}"
         create -c -t "$CEN_OPT_ROOT$DAT_UPDTHOOK" <<!EOF || return 1
-#!/bin/bash
+#!/usr/bin/bash
 $CEN_TOOLS/$CEN_NAME initrd update "\$2"
 !EOF
         system -e -p -- chmod 770 "$CEN_OPT_ROOT$DAT_UPDTHOOK"
@@ -410,14 +411,24 @@ actionRemove() {
 }
 
 # ------------------------------------------------------------------------------
-# set root: <config>|- <label>|-
+# set root: <config>|-|. <label>|-
+#
+#   config: <name>  use cmdline-<name>.txt
+#           -       use cmdline-default.txt
+#           .       use cmdline.txt
+#
+#   label:  <path>  example: /dev/sda       -> root=/dev/sda
+#           <label> example: cent9_root     -> root=LABEL=<label>
+#           <uuid>  example: abcd1234-03    -> root=PARTUUID=<uuid>
+#           -       1st try 'rootfs' 2 try <hostname>_(vol0|root|rootfs)
+####           .       use PARTUUID
 # ------------------------------------------------------------------------------
 actionRoot() {
     do_folder
 
     local conf="${1:-.}" ; shift
     local iden="${1:--}" ; shift
-    [ "$conf" = '.' ] && conf= ; [ "$conf" = '-' ] && conf="default"
+    [ "$conf" = '.' ] && conf= ; [ "$conf" = '-' ] && conf='default'
     conf="cmdline${conf:+-}$conf.txt"
 
     if ! [ -e "$conf" ] ; then
@@ -426,9 +437,26 @@ actionRoot() {
 
     # no label arg, try rootfs or default to <host>
     local item part
+    #if [ "$iden" = '.' ] ; then
+    #    local list indx=0
+    #    if [ -z "$CEN_OPT_DEVICE" ] ; then
+    #        error "Option '--device' missing" ; return
+    #    fi
+    #    system -e -p -a list -- blkid --probe -o value -s TYPE -s UUID "$CEN_OPT_DEVICE" || return
+    #    while [ -n "${list[indx]}" ] ; do
+    #        if [ "${list[indx]}" = 'ext4' -o "${list[indx]}" = 'btrfs' ] ; then
+    #            iden="${list[indx+1]}" ; part="/dev/disk/by-partuuid/$iden"
+    #            message -a -p "Found 'PARTUUID=%s' with '%s' filesystem" "$iden" "${list[indx]}"
+    #            break
+    #        fi
+    #        ((indx += 2))
+    #    done
+    #    if [ "$iden" = '.' ] ; then
+    #        error 'UUID not found' ; return
+    #    fi
     if [ "$iden" = '-' ] ; then
         if [ -b "/dev/disk/by-label/rootfs" ] ; then
-            parg="/dev/disk/by-label/rootfs"
+            part="/dev/disk/by-label/rootfs"
         else
             iden="$CEN_OPT_HOST"
         fi
@@ -451,11 +479,16 @@ actionRoot() {
     trace -a "Config: $conf  Partition: $part"
 
     # get puid for label
-    local karg kuid kcmd puid
-    [ -e "$part" ] &&
-        for puid in "/dev/disk/by-partuuid/"* "" ; do
+    local karg kuid kcmd puid labl
+    if [ -e "$part" ] ; then
+        for labl in "/dev/disk/by-label/"* '' ; do
+            [ "$labl" -ef "$part" ] && break
+        done
+        labl="${labl##*/}"
+        for puid in "/dev/disk/by-partuuid/"* '' ; do
             [ "$puid" -ef "$part" ] && break
         done
+    fi
 
     if [ -z "$puid" ] ; then
         if [ -n "$CEN_OPT_FORCE" ] ; then
@@ -466,7 +499,7 @@ actionRoot() {
         fi
     else
         puid="${puid##*/}"
-        message -a -p $"Found PARTUUID '%s' with label '%s'" "$puid" "${part##*/}"
+        message -a -p $"Found PARTUUID '%s' with label '%s'" "$puid" "${labl:-<none>}"
     fi
 
     # modify kernel command line
@@ -475,8 +508,11 @@ actionRoot() {
         case "$item" in
             root=LABEL=*)
                 kuid="${item##*=}" ; part="${part##*/}"
-                if [ "$kuid" = "$part" ] ; then
-                    message -a $"Root LABEL is current"
+                if [ "$CEN_OPT_UUID" = 1 ] ; then
+                    confirm -y -a -f $"Change root PARTUUID from '%s' to '%s'" "$kuid" "$puid" || return
+                    item="root=PARTUUID=$puid"
+                elif [ "$kuid" = "$part" ] ; then
+                    message -a $"Root LABEL is current, no update" ; return
                 else
                     confirm -y -a -f $"Change root LABEL from '%s' to '%s'" "$kuid" "$part" || return
                     item="root=LABEL=$part"
@@ -485,7 +521,7 @@ actionRoot() {
             root=PARTUUID=*)
                 kuid="${item##*=}"
                 if [ "$kuid" = "$puid" ] ; then
-                    message -a $"Root PARTUUID is current"
+                    message -a $"Root PARTUUID is current, no update" ; return
                 else
                     confirm -y -a -f $"Change root PARTUUID from '%s' to '%s'" "$kuid" "$puid" || return
                     item="root=PARTUUID=$puid"
@@ -496,11 +532,12 @@ actionRoot() {
     done
 
     if [ -z "$kuid" ] ; then
-        warning -a $"Found no 'root=PARTUUID' or 'root=LABEL=...' in kernel command line"
-    else
-        kcmd="${kcmd:1}"
-        create -t -v kcmd -- "$conf"
+        error $"Found no 'root=PARTUUID' or 'root=LABEL=...' in kernel command line"
+        return
     fi
+    kcmd="${kcmd:1}"
+    create -t -v kcmd -- "$conf"
+    message -a "Updated:" "$conf" # (PWD=$PWD)"
 }
 
 # ------------------------------------------------------------------------------
@@ -538,6 +575,8 @@ options() {
         optarg 'nocheck'     -   -f  ;;         # flag
     -R|--roo|--root)
         optarg 'root'        -   -d  ;;         # existing folder
+    -U|--uui|--uuid)
+        optarg 'uuid'        -   -o  ;;         # existing folder
     esac
 }
 
@@ -572,12 +611,13 @@ actions() {
 # ------------------------------------------------------------------------------
 usage() {
     usageset -o - \
-       -o '-B --boot    <fldr>' $"path of boot folder      (default: /boot)" \
+       -o '-B --boot    <fldr>' $"path of boot folder         (default: /boot)" \
        -o '-D --device  <name>' $"raspberry boot device" \
        -o '-H --host    <host>' $"override host name" \
-       -o '-L --legacy  <lega>' $"pre-bookworm boot layout (default: auto)" \
+       -o '-L --legacy  <auto>' $"pre-bookworm boot layout    (default: auto)" \
        -o '-N --nocheck'        $"don't check boot partition" \
-       -o '-R --root    <fldr>' $"path of root folder      (default: /)"
+       -o '-R --root    <fldr>' $"path of root folder         (default: /)" \
+       -o '-U --uuid    <auto>' $"use PARTUUID in cmdline.txt (default: auto)"
 
     usageset \
        -a 'config <config>|- [<overlay>]' \
@@ -594,13 +634,13 @@ usage() {
        -a 'show'                $"Show current boot configuration"
 
     usageset \
+       -p '<auto>'      $"one of: 0|off 1|on 2|auto" \
        -p '<carg>'      $"extra argument(s) for 'cmdline'" \
        -p '<config>'    $"a configuration name (for cmdline-*.txt)" \
        -p '<entr>'      $"name of a 'cmdline' entry:" 'cmdline-<entr>.txt' \
        -p '<event>'     $"'create', 'update' or 'remove' (uninstall hook)" \
        -p '<fldr>'      $"any existing folder (must contain 'overlays')" \
        -p '<host>'      $"target host name (default: $HOSTNAME)" \
-       -p '<lega>'      $"one of: 0|off 1|on 2|auto" \
        -p '<name>'      $"system name, label or blockdevice" \
        -p '<overlay>'   $"an overlay file name (for config-*.txt)" \
        -p '<root>'      $"parameter for root=... (use '-' to disable, '+' for default)"
diff --git a/centaurisoho b/centaurisoho
--- a/centaurisoho
+++ b/centaurisoho
@@ -317,10 +317,11 @@ get_architecture() {
 # Options:      -n  do not check seed, do not change working dir
 #               -q  like -n but no error messages
 #               -f  do not check seed
+#               -r  like -w with fallback to repository
 #               -w  just get workspace, do not change working dir
 # ------------------------------------------------------------------------------
 get_base() {
-    local nmsg ; [ "$1" = '-q' -o "$1" = '-w' ] && nmsg=1
+    local nmsg ; [ "$1" = '-q' -o "$1" = '-r' -o "$1" = '-w' ] && nmsg=1
     if [ -n "$SOHO_WORKSPACE" ] ; then              # previous call
         [ "$1" = '-n' -o -n "$nmsg" ] && return 0   # dont change folder
         folder -f -c -- "$SOHO_WORKSPACE" ; return 0
@@ -334,10 +335,12 @@ get_base() {
         splitkeyval  "$CEN_OPT_CURRENT" SOHO_DISTRO SOHO_CONFIG ':'
     if [ -z "$SOHO_WORKSPACE" ] ; then
         [ "$1" = '-q' ] && return 1
-        quit -e "No known workspace, use option '--base=<fldr>'"
+        [ "$1" = '-r' ] || quit -e "No known workspace, use option '--base=<fldr>'"
+        get_repository ; return
     elif [ ! -d "$SOHO_WORKSPACE/dists" ] ; then
         [ "$1" = '-q' ] && return 1
-        quit -e "Not a valid workspace" "$SOHO_WORKSPACE"
+        [ "$1" = '-r' ] || quit -e "Not a valid workspace:" "$SOHO_WORKSPACE"
+        get_repository ; return
     elif [ "$1" = '-w' ] ; then
         return 0
     elif [ -z "$SOHO_DISTRO" -o -z "$SOHO_CONFIG" ] ; then
@@ -445,6 +448,24 @@ get_path() {
     *)      fatal -t '?' "$1"
     esac
     printf -v "$3" '%s' "$_sout"
+}
+
+# ------------------------------------------------------------------------------
+# get repository path: -no args-
+# ------------------------------------------------------------------------------
+get_repository() {
+    [ -n "$DAT_REPOSITORY" ] && return 0
+    if [ -n "$SOHO_DNAME" ] ; then
+        DAT_REPOSITORY="$CEN_ROOT/configs/$SOHO_DISTRO/$SOHO_DNAME"
+        return 0
+    elif [ -d "$CEN_ROOT/shared" ] ; then
+        resolve -e -m $CEN_ROOT/shared/.. || return
+        DAT_REPOSITORY="$CEN_RESOLVE"
+        return 0
+    fi
+    error -n "Missing '$CEN_ROOT/shared', please create manually by" \
+             "running: ln -s $CEN_ROOT/configs/<dist>/<dnam>/@shared $CEN_ROOT/shared"
+    return 1
 }
 
 # ------------------------------------------------------------------------------
@@ -575,7 +596,7 @@ get_update() {
             elif [ -h "$file" ] ; then
                 list+=("$file")
             else
-                trace -a -c "File not in repo" "${file#$CEN_ROOT/}"
+                message -a -c "File not in repo" "${file#$CEN_ROOT/}"
                 ((miss += 1))
             fi
         done
@@ -603,7 +624,7 @@ get_value() {
     [ "$_prom" = '-' -o "${_dflt:--}" != '-' ] && _prom="$_dflt"
 
     printf -v _text '%s%%s[%s]' "$4" "$_prom"
-    local _leng ; printf -v _leng '%60s'
+    local _leng ; printf -v _leng '%56s'
     local _fill=$((${#_leng} - ${#_text}))
     [ "$_fill" -lt 1 ] && _fill=1
     printf -v _text "$_text" "${_leng::_fill}"
@@ -643,7 +664,7 @@ get_yesno() {
 # ------------------------------------------------------------------------------
 run_installer() {
     [ -x './installer' ] || quit -e "Install helper not found:" "$PWD/installer"
-    local opts=('./installer' "$@") # "$1" "${2:--}" "${3:--}")
+    local opts=('./installer' "$@")
     DAT_SELF="$CEN_NAME"
     dryrun -s "source ${opts[@]}" && return
     trace -a -c "Sourcing" "${opts[@]}"
@@ -898,8 +919,10 @@ actionDistr() {
 # Run docviewer
 # ------------------------------------------------------------------------------
 actionDocview() {
-    get_base -w || return                           # get base folder
-    embed -x -v -- "$SOHO_WORKSPACE/README/docviewer.dynamic" "$@"
+    get_base -r || return                           # get base folder
+    local docv="$SOHO_WORKSPACE/README/docviewer.dynamic"
+    [ -x "$docv" ] || docv="$DAT_REPOSITORY/../@soho/docviewer"
+    embed -x -v -- "$docv" "$@"
 }
 
 # ------------------------------------------------------------------------------
@@ -1136,7 +1159,7 @@ actionPack() {
 
     local ysav="$CEN_YESNO" ; CEN_YESNO='y'
     local dirs=() dist item seed fldr noex
-    for item in "dists"/[!@]* ; do
+    for item in 'dists'/[!@]* ; do
         [ -d "$item" ] || continue
         dist="${item##*/}"
 
@@ -1163,6 +1186,7 @@ actionPack() {
         confirm -y -f "Remove %s static|dynamic|configs folders" "${#dirs[@]}" &&
             remove -d -- "${dirs[@]}" 'static' 'dynamic'
     fi
+    remove 'dists'/*/@seed/seed-*-*.tgz
     matchpath -a noex -n -- * ; remove -- "${noex[@]}"
 }
 
@@ -1273,20 +1297,9 @@ succeed:
 #   <dflt>      alternate for missing <path>, no error if '-'
 # ------------------------------------------------------------------------------
 actionRepository() {
+    # get base folder and repository path
     get_base -n || return
-
-    # get repository path
-    if [ -z "$DAT_REPOSITORY" ] ; then
-        if [ -n "$SOHO_DNAME" ] ; then
-            DAT_REPOSITORY="$CEN_ROOT/configs/$SOHO_DISTRO/$SOHO_DNAME"
-        elif [ -d "$CEN_ROOT/shared" ] ; then
-            resolve -e -m $CEN_ROOT/shared/.. || return
-            DAT_REPOSITORY="$CEN_RESOLVE"
-        else
-            error -n "Missing '$CEN_ROOT/shared', please create manually by" \
-                     "running: ln -s $CEN_ROOT/configs/<dist>/<dnam>/@shared $CEN_ROOT/shared"
-        fi
-    fi
+    get_repository || return
 
     # no args: print repository information
     : ${DAT_HOST:=$HOSTNAME}
@@ -1559,10 +1572,10 @@ actionRestore() {
     [ "$name" != "$host" ] && opts+=(-N "$name")
 
     if [ -n "$rasp" ] ; then
-        confirm -a -y -f '%-46s' "Install '$name' in 'raspberry' mode" || return
+        confirm -a -y -f '%-48s' "Install '$name' in 'raspberry' mode" || return
         embed -z -v centauridisk "${opts[@]}" -M -R 512 -P$swap -- "${labl[1]}"
     else
-        confirm -a -y -f '%-46s' "Install '$name' in 'x86/pc' mode" || return
+        confirm -a -y -f '%-48s' "Install '$name' in 'x86/pc' mode" || return
         embed -z -v centauridisk "${opts[@]}" -P$swap -- "${labl[1]}"
     fi
 
@@ -1830,7 +1843,6 @@ actionVacuum() {
 actionWorkspace() {
     # archive workspace
     if [ "${1::3}" = 'arc' ] ; then
-       # get_base -f || return                       # change dir to base folder
         actionPack ; error -t || return
         run_installer 'archive' "$2"
         return
@@ -1864,8 +1876,9 @@ actionWorkspace() {
     message -a -c $"Repository" "$repo"
 
     if [ "$1" = 'get' ] ; then
+        # copy content of master folder
         embed -z centauricopy sync "$repo/@soho/master" . || return
-        run_installer unpack
+        CEN_OPT_BASE="$PWD" ; actionUnpack
     else
         for dist in dists/[a-z]* ; do
             [ -d "$dist/static" ] || continue
